###############################################################################
# Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
#
# See LICENSE for license information.
###############################################################################

"""Registry of the ops that ``validate_perf_model.py`` can validate.

Each op is declared once with :func:`register`. The decorated builder turns
CLI dimensions (an ``argparse.Namespace``) into a synthetic TraceLens event,
and the registry pairs it with the perf-model class that scores that event.
``OP_REGISTRY[key]["model_fn"](args)`` returns ``(flops, bytes, precision)``.

Adding an op
------------
1. Add a ``@register("<key>", ...)`` builder below, in the section for its
   op family. ``model=(source, name)``: ``source`` is a module constant
   (``PERF_MODEL_EXT``, ``ATTN_EXT``, ``CORE_OP_MAP``, ...) or an extension
   env var (``DSV3_EXT``, ``DSV4_EXT``, ``KIMI_EXT``); ``name`` is the class
   name or its trace op name. ``trace_names`` lists the trace op names that
   map to the op in ``--from-report-dir`` mode.
2. Add ``test_<key>(**kwargs)`` to the matching ``tests/<module>.py``. The
   runner finds it by name and rocprofv3 profiles it.
3. Ops validated only from a report directory have no builder: add them to
   the ``_CSV_ONLY_OPS`` table and to ``tests/_generic.OP_CALL_SPEC``.
"""

import functools
import importlib
import importlib.util
import inspect
import os
import re
import sys
from pathlib import Path

# Constants
PERF_MODEL_EXT = "TraceLens.PerfModel.extensions.perf_model_extensions"
MOE_EXT = "TraceLens.PerfModel.extensions.moe_perf_model_extensions"
RMSNORM_EXT = "TraceLens.PerfModel.extensions.rmsnorm_perf_model_extensions"
ATTN_EXT = "TraceLens.PerfModel.extensions.attention_perf_model_extensions"
PERF_MODEL = "TraceLens.PerfModel.perf_model"
CORE_OP_MAP = "TraceLens.PerfModel.torch_op_mapping"

# Env vars naming perf-model extension files that live outside TraceLens.
DSV3_EXT = "DSV3_TRIAGE_EXTENSION"
DSV4_EXT = "DSV4_TRIAGE_EXTENSION"
KIMI_EXT = "KIMI_K3_TRIAGE_EXTENSION"
_EXTENSION_HINTS = {
    DSV3_EXT: "the triage extension file generated by "
    "run_other_bucket_triage.py --emit-extension",
    DSV4_EXT: "the triage extension file generated by "
    "run_other_bucket_triage.py --emit-extension",
    KIMI_EXT: "the Kimi-K3 perf model extension file",
}

_PARENTS = Path(__file__).resolve().parents
# <repo>/TraceLens/Agent/PerfModel/validate-perf-model/; staging copies of the
# skill may sit fewer than five levels deep.
REPO_ROOT = str(_PARENTS[4] if len(_PARENTS) > 4 else _PARENTS[-1])

_BF16 = "c10::BFloat16"
_FP8 = "c10::Float8_e4m3fn"
_E8M0 = "c10::Float8_e8m0fnu"
_TRACE_DTYPE_MAP = {
    "bf16": "c10::BFloat16",
    "fp16": "c10::Half",
    "fp32": "float",
    "fp64": "double",
    "fp8": "c10::Float8_e4m3fnuz",
    "fp8_e4m3fn": "c10::Float8_e4m3fn",
    "fp8_e4m3fnuz": "c10::Float8_e4m3fnuz",
    "fp8_e5m2": "c10::Float8_e5m2",
    "fp4": "c10::Float4_e2m1fn_x2",
    "fp4x2": "c10::Float4_e2m1fn_x2",
    "i8": "signed char",
    "u8": "unsigned char",
    "i32": "int",
    "u16": "unsigned short",
    "u32": "unsigned int",
}
_TRACE_DTYPE_NAMES = (
    "unsigned short",
    "unsigned char",
    "unsigned int",
    "signed char",
    "int",
    "float",
    "double",
    "Half",
    "BFloat16",
)
_UNIFIED_ATTN_ANNOTATION_RE = re.compile(
    r"execute_(?P<iter>\d+)"
    r"_context_(?P<ctx_req>\d+)\(sq(?P<ctx_sq>\d+)sk(?P<ctx_sk>\d+)"
    r"sqsq(?P<ctx_sqsq>\d+)sqsk(?P<ctx_sqsk>\d+)\)"
    r"_generation_(?P<gen_req>\d+)\(sq(?P<gen_sq>\d+)sk(?P<gen_sk>\d+)"
    r"sqsq(?P<gen_sqsq>\d+)sqsk(?P<gen_sqsk>\d+)\)"
)

# (fn_name, description, trace_names); all share _activation_event.
_ACTIVATION_OPS = (
    (
        "silu_and_mul",
        "SiLU-gated activation (SwiGLU gate*up)",
        ("aiter::silu_and_mul", "_C::silu_and_mul"),
    ),
    ("gelu_and_mul", "GELU-gated activation", ("aiter::gelu_and_mul",)),
    ("gelu_tanh_and_mul", "GELU-tanh-gated activation", ("aiter::gelu_tanh_and_mul",)),
)
# (key, category, description, trace_name) for ops with no CLI builder. In
# --from-report-dir mode the prediction comes from the traced event and
# tests/_generic.OP_CALL_SPEC replays the traced call.
_CSV_ONLY_OPS = (
    (
        "batched_gemm_a16wfp4_",
        "gemm",
        "AITER batched BF16 x MXFP4 GEMM (triton)",
        "aiter::batched_gemm_a16wfp4_",
    ),
    (
        "fused_qk_rmsnorm",
        "norm",
        "AITER fused Q/K RMSNorm",
        "aiter::_fused_qk_rmsnorm_kernel",
    ),
    (
        "biased_grouped_topk_hip",
        "moe",
        "AITER biased grouped top-k MoE routing (HIP)",
        "aiter::biased_grouped_topk_hip",
    ),
    (
        "moe_sorting_fwd",
        "moe",
        "AITER MoE token sorting / expert bucketing",
        "aiter::moe_sorting_fwd",
    ),
    (
        "mxfp4_moe_sort_hip",
        "moe",
        "AITER MXFP4 MoE scale sorting (HIP)",
        "aiter::mxfp4_moe_sort_hip",
    ),
    (
        "sgl_kernel_silu_and_mul",
        "activation",
        "SGLang sgl_kernel SiLU-and-mul (needs an SGLang runtime)",
        "sgl_kernel::silu_and_mul",
    ),
    (
        "vllm_concat_and_cache_mla",
        "vllm_attention",
        "vLLM MLA KV-cache concat + write",
        "_C_cache_ops::concat_and_cache_mla",
    ),
    (
        "vllm_concat_mla_q",
        "vllm_attention",
        "vLLM MLA query concat (nope + pe)",
        "_C_cache_ops::concat_mla_q",
    ),
    (
        "vllm_per_token_group_fp8_quant",
        "vllm_quant",
        "vLLM per-token-group FP8 quantization",
        "_C::per_token_group_fp8_quant",
    ),
    (
        "flash_attn_varlen_forward",
        "attention",
        "flash-attn varlen forward (packed prefill)",
        "flash_attn::_flash_attn_varlen_forward",
    ),
)

OP_REGISTRY = {}
TRACE_NAME_TO_OP = {}
_EXTENSION_CACHE = {}


def register(
    key,
    *,
    category,
    description,
    model=None,
    defaults=None,
    required_args=None,
    trace_names=(),
    csv_harness=False,
    perf_model_only=False,
):
    """Register op ``key`` in :data:`OP_REGISTRY`; decorates its event builder.

    ``model`` is ``(source, name)`` as accepted by :func:`resolve_model_class`,
    or ``None`` for ops validated only from a report directory (decorate
    ``None`` for those). ``defaults`` seed CLI args that the user leaves
    unset; ``required_args`` (default: all ``defaults`` keys) are the ones
    reported for the op. ``csv_harness`` replays report rows through
    ``test_<key>`` with dimensions extracted from the row instead of the
    generic runner. ``perf_model_only`` skips profiling for ops whose kernel
    cannot run standalone.
    """
    if key in OP_REGISTRY:
        raise ValueError(f"Op '{key}' is registered twice")
    defaults = dict(defaults or {})

    def decorator(build_event):
        OP_REGISTRY[key] = {
            "category": category,
            "description": description,
            "model": model,
            "build_event": build_event,
            "model_fn": functools.partial(_evaluate, key),
            "defaults": defaults,
            "required_args": list(defaults if required_args is None else required_args),
            "trace_names": tuple(trace_names),
            "csv_harness": csv_harness,
            "perf_model_only": perf_model_only,
        }
        for trace_name in trace_names:
            if trace_name in TRACE_NAME_TO_OP:
                raise ValueError(
                    f"Trace name '{trace_name}' maps to both "
                    f"'{TRACE_NAME_TO_OP[trace_name]}' and '{key}'"
                )
            TRACE_NAME_TO_OP[trace_name] = key
        return build_event

    return decorator


def resolve_model_class(source, name):
    """Return the perf-model class ``name`` from ``source``.

    ``source`` is a TraceLens module path or an extension env var. ``name`` is
    looked up in the source's trace-name map first (``perf_model_extension``
    for extension files, ``op_to_perf_model_class_map`` for modules), then as
    an attribute, so both trace op names and class names resolve.
    """
    if source in _EXTENSION_HINTS:
        module = _load_extension(source)
        mapping = getattr(module, "perf_model_extension", {})
    else:
        ensure_tracelens_importable()
        module = importlib.import_module(source)
        mapping = getattr(module, "op_to_perf_model_class_map", {})
    if name in mapping:
        return mapping[name]
    return getattr(module, name)


def model_source(key):
    """Return ``(class_name, source_file, source_line)`` for op ``key``'s model.

    ``source_file`` is relative to the repo root. The line is 0 when the class
    cannot be loaded, e.g. because its extension env var is unset.
    """
    model = OP_REGISTRY[key]["model"] if key in OP_REGISTRY else None
    if model is None:
        return (key, "unknown", 0)
    source, name = model
    try:
        cls = resolve_model_class(source, name)
        src_file = os.path.relpath(inspect.getfile(cls), REPO_ROOT)
        _, src_line = inspect.getsourcelines(cls)
    except (ImportError, AttributeError, KeyError, OSError, TypeError):
        if source in _EXTENSION_HINTS:
            return (name, f"${source}", 0)
        return (name, source.replace(".", "/") + ".py", 0)
    return (cls.__name__, src_file, src_line)


def tuple_to_list(obj):
    """Recursively convert tuples to lists for event dict compatibility."""
    if isinstance(obj, tuple):
        return [tuple_to_list(x) for x in obj]
    return obj


def run_perf_model_from_event(
    trace_name,
    input_dims,
    input_types,
    input_strides,
    concrete_inputs,
    attn_params=None,
):
    """Evaluate the perf model for a ``unified_perf_summary.csv`` row.

    Builds the event from the row's columns and resolves the class from
    TraceLens's ``op_to_perf_model_class_map``, then from the
    ``perf_model_extension`` map of every extension whose env var is set.
    """
    ensure_tracelens_importable()
    event = {
        "name": trace_name,
        "args": {
            "Input Dims": tuple_to_list(input_dims),
            "Input type": list(input_types) if input_types else [],
        },
    }
    if input_strides:
        event["args"]["Input Strides"] = tuple_to_list(input_strides)
    if concrete_inputs:
        event["args"]["Concrete Inputs"] = list(concrete_inputs)
    if attn_params:
        event["annotation"] = _chunk_stats_annotation(attn_params)
    event["kernel_names"] = ["placeholder_kernel"]
    event["kernel_details"] = [{"name": "placeholder_kernel"}]
    try:
        from TraceLens.PerfModel.torch_op_mapping import op_to_perf_model_class_map
    except ImportError:
        from TraceLens.PerfModel.extensions.pseudo_ops_perf_utils import (
            get_pseudo_op_mappings,
        )

        op_to_perf_model_class_map = get_pseudo_op_mappings()
    model_cls = op_to_perf_model_class_map.get(trace_name)
    for env_var in _EXTENSION_HINTS:
        if model_cls is not None:
            break
        if os.environ.get(env_var):
            extension_map = getattr(
                _load_extension(env_var), "perf_model_extension", {}
            )
            model_cls = extension_map.get(trace_name)
    if model_cls is None:
        raise ValueError(f"No perf model class found for trace name '{trace_name}'")
    model = model_cls(event)
    return (model.flops(), model.bytes(), model.get_compute_precision())


def ensure_tracelens_importable():
    """Add the TraceLens repo root to ``sys.path`` unless TraceLens is installed."""
    if importlib.util.find_spec("TraceLens") is None and REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)
    return None


def _evaluate(key, args):
    """Build op ``key``'s event from ``args`` and score it with its perf model."""
    entry = OP_REGISTRY[key]
    if entry["model"] is None:
        raise NotImplementedError(
            "This op is only validated via --from-report-dir, which derives the "
            "prediction from the traced event rather than from CLI dimensions."
        )
    cls = resolve_model_class(*entry["model"])
    model = cls(entry["build_event"](args))
    return (model.flops(), model.bytes(), model.get_compute_precision())


def _load_extension(env_var):
    """Load (and cache) the extension module named by env var ``env_var``."""
    path = os.environ.get(env_var)
    if not path:
        raise ImportError(
            f"{env_var} is not set. Point it at {_EXTENSION_HINTS[env_var]}."
        )
    if path not in _EXTENSION_CACHE:
        ensure_tracelens_importable()
        spec = importlib.util.spec_from_file_location(env_var.lower(), path)
        if spec is None or spec.loader is None:
            raise ImportError(f"Could not load the {env_var} extension from '{path}'.")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        _EXTENSION_CACHE[path] = module
    return _EXTENSION_CACHE[path]


def _chunk_stats_annotation(attn_params):
    """Rebuild a trace attention annotation from InferenceAttention CSV params."""

    def _int(name):
        value = attn_params.get(name, 0)
        if value is None or str(value) in ("nan", ""):
            return 0
        return int(float(value))

    c_sq, c_sk, c_sqsq, c_sqsk = (_int(f"c_{s}") for s in ("sq", "sk", "sqsq", "sqsk"))
    g_sq, g_sk, g_sqsq, g_sqsk = (_int(f"g_{s}") for s in ("sq", "sk", "sqsq", "sqsk"))
    if not any((g_sq, g_sk, g_sqsq, g_sqsk)):
        return f"attn_0_0_{c_sq}_{c_sqsq}_0_0_0"
    # Chunk-stats annotation parsed by InferenceAttention._parse_chunk_stats.
    # The req counts (context_/generation_) are not parsed; use 0/1 markers.
    ctx_req = 1 if c_sq else 0
    gen_req = 1 if g_sq else 0
    return (
        f"execute_0_context_{ctx_req}(sq{c_sq}sk{c_sk}sqsq{c_sqsq}sqsk{c_sqsk})"
        f"_generation_{gen_req}(sq{g_sq}sk{g_sk}sqsq{g_sqsq}sqsk{g_sqsk})"
    )


def _trace_dtype_str(name, default):
    """Map a user-facing dtype string ("bf16", "fp8", ...) to a trace ``Input type``.

    Returns ``default`` when ``name`` is None or empty. A fully-qualified trace
    string (e.g. ``"c10::BFloat16"``) is returned unchanged so callers can pass
    either form.
    """
    if name is None or name == "":
        return default
    key = str(name).strip()
    lower = key.lower()
    if lower in _TRACE_DTYPE_MAP:
        return _TRACE_DTYPE_MAP[lower]
    if "::" in key or key in _TRACE_DTYPE_NAMES:
        return key
    raise ValueError(
        f"Unknown dtype string {name}. Known short names: {sorted(_TRACE_DTYPE_MAP)}"
    )


def _moe_dtypes_from_args(args, defaults):
    """Resolve ``(in_dtype, w_dtype, out_dtype)`` trace strings from ``args``.

    ``defaults`` is a 3-tuple of trace strings used when the corresponding CLI
    flag is unset.
    """
    in_t = _trace_dtype_str(getattr(args, "in_dtype", None), defaults[0])
    w_t = _trace_dtype_str(getattr(args, "w_dtype", None), defaults[1])
    out_t = _trace_dtype_str(getattr(args, "out_dtype", None), defaults[2])
    return (in_t, w_t, out_t)


def _dtype_from_args(args, attr_name, default_trace_str):
    """Resolve a single dtype attribute on ``args`` to a trace ``Input type``."""
    return _trace_dtype_str(getattr(args, attr_name, None), default_trace_str)


def _kv_dtype_from_args(args, default_trace_str):
    """Resolve ``args.kv_dtype`` (paged-attention KV cache dtype)."""
    return _trace_dtype_str(getattr(args, "kv_dtype", None), default_trace_str)


def _parse_unified_attention_annotation(annotation):
    """Parse a vLLM ``execute_..._context_..._generation_(...)`` annotation.

    Returns a dict with ctx_req/ctx_sq/ctx_sk/ctx_sqsq/ctx_sqsk and
    gen_req/gen_sq/gen_sk/gen_sqsq/gen_sqsk, or None if the annotation is
    falsy / does not match.
    """
    if not annotation:
        return None
    m = _UNIFIED_ATTN_ANNOTATION_RE.search(str(annotation))
    if not m:
        return None
    return {k: int(v) for k, v in m.groupdict().items()}


def _a8w8_blockscale_event(name, args):
    """Event for an FP8 / INT8 block-scaled GEMM laid out like ``gemm_a8w8_blockscale``."""
    K = args.K
    N = args.N
    M = args.M
    block_k = getattr(args, "block_k", None) or 128
    nkb = (K + block_k - 1) // block_k
    in_t = _dtype_from_args(args, "in_dtype", "unsigned char")
    w_t = _dtype_from_args(args, "w_dtype", "unsigned char")
    scl_t = _dtype_from_args(args, "scale_dtype", "float")
    return {
        "name": name,
        "args": {
            "Input Dims": [[M, K], [N, K], [M, nkb], [N, nkb]],
            "Input type": [in_t, w_t, scl_t, scl_t],
            "Input Strides": [[K, 1], [K, 1], [nkb, 1], [nkb, 1]],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }


def _activation_event(fn_name, args):
    """Event for ``aiter::<fn_name>`` gated activations (``out = act(gate) * up``).

    Reads ``in_dtype`` (slot ``[1]``, the gate||up input) and ``out_dtype``
    (slot ``[0]``). Defaults to BF16 for both.
    """
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    out_t = _dtype_from_args(args, "out_dtype", "c10::BFloat16")
    return {
        "name": f"aiter::{fn_name}",
        "args": {
            "Input Dims": [[M, N], [M, 2 * N]],
            "Input type": [out_t, in_t],
            "Input Strides": [[N, 1], [2 * N, 1]],
        },
    }


def _varlen_annotation(args):
    """Return ``(annotation, total_q, total_kv)`` for a varlen prefill call.

    The ``_varlen_*`` attributes are filled in by
    ``validate_perf_model._populate_varlen_attention_args`` from the same seed
    and scenario the test uses; without them the call is one ``seq_len``
    sequence. The generation block is zero because the kernels are
    prefill-only; ``c_sqsk`` equals ``c_sqsq`` for self-attention.
    """
    S = args.seq_len
    c_sq = getattr(args, "_varlen_c_sq", S)
    c_sqsq = getattr(args, "_varlen_c_sqsq", S * S)
    total_q = getattr(args, "_varlen_total_q", S)
    total_kv = getattr(args, "_varlen_total_kv", S)
    c_sqsk = getattr(args, "_varlen_c_sqsk", c_sqsq)
    n_ctx = getattr(args, "_varlen_n_ctx", 1)
    annotation = (
        f"execute_0_context_{n_ctx}(sq{c_sq}sk{total_kv}sqsq{c_sqsq}sqsk{c_sqsk})"
        f"_generation_0(sq0sk0sqsq0sqsk0)"
    )
    return (annotation, total_q, total_kv)


def _build_unified_attention_event(name, args):
    """Event for a unified (paged-KV) attention call named ``name``.

    A valid ``execute_*`` ``args.annotation`` is passed through verbatim.
    Otherwise one is synthesized from ``num_decode_seqs`` / ``ctx_len`` /
    ``prefill_seq_len`` (falling back to ``seq_len`` single-token decodes).
    Q / KV token totals are then read back from the annotation, the same way
    real vLLM traces are handled.
    """
    d = args.head_dim
    H_KV = args.num_heads_kv
    H_Q = args.num_heads_q
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    kv_t = _kv_dtype_from_args(args, "c10::Float8_e4m3fnuz")
    annotation_str = getattr(args, "annotation", None)
    if not _parse_unified_attention_annotation(annotation_str):
        num_decode_seqs = getattr(args, "num_decode_seqs", None)
        ctx_len_arg = getattr(args, "ctx_len", None)
        p_len = int(getattr(args, "prefill_seq_len", 0) or 0)
        _seq_fallback = int(getattr(args, "seq_len", None) or 256)
        n_decode = (
            int(num_decode_seqs) if num_decode_seqs is not None else _seq_fallback
        )
        kv = int(ctx_len_arg) if ctx_len_arg is not None else _seq_fallback
        g_sqsk = n_decode * kv
        generation = (
            f"_generation_{n_decode}(sq{n_decode}sk{g_sqsk}sqsq{n_decode}sqsk{g_sqsk})"
        )
        if p_len > 0:
            c_sqsk = p_len * p_len
            context = f"context_1(sq{p_len}sk{p_len}sqsq{c_sqsk}sqsk{c_sqsk})"
        else:
            context = "context_0(sq0sk0sqsq0sqsk0)"
        annotation_str = f"execute_0_{context}{generation}"
    parsed = _parse_unified_attention_annotation(annotation_str)
    if parsed is None:
        raise ValueError(f"Cannot parse {name} annotation: {annotation_str!r}")
    sum_q = parsed["ctx_sq"] + parsed["gen_sq"]
    sum_kv = parsed["ctx_sk"] + parsed["gen_sk"]
    return {
        "name": name,
        "annotation": annotation_str,
        "args": {
            "Input Dims": [[sum_q, H_Q, d], [sum_kv, H_KV, d]],
            "Input type": [in_t, kv_t],
        },
    }


def _gdn_event(name, args, H_K, annotation):
    """Event for a Gated Delta Network call ``(mixed_qkv, b, a, core_attn_out, layer)``.

    Slot ``[0]`` sets the compute precision; ``gdn_attention_core.bytes()``
    hardcodes 2 BPE, so the dtype only changes the test runner side.
    """
    T = args.seq_len
    H_V = args.num_heads_kv
    d_k = args.head_dim
    d_v = args.head_dim
    D = 2 * H_K * d_k + H_V * d_v
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    return {
        "name": name,
        "annotation": annotation,
        "args": {
            "Input Dims": [[T, D], [T, H_V], [T, H_V], [T, H_V, d_v], []],
            "Input type": [in_t, in_t, in_t, in_t, ""],
        },
    }


def _dsv3_flydsl_moe_event(name, M, K, N, E, topk):
    """Build a parent ``aiter::fused_moe_`` style event for the flydsl pseudo ops.

    Layout matches ``_flydsl_extract_param_details``:
      dims[0] = [tokens, hidden]
      dims[1] = [E, 2*inter_dim, hidden/2]   (w1, fp4-packed K)
      dims[2] = [E, hidden, inter_dim/2]     (w2, fp4-packed K)
      dims[3] = [tokens, topk]
    """
    token, hidden, inter = M, K, N
    return {
        "name": name,
        "args": {
            "Input Dims": [
                [token, hidden],
                [E, 2 * inter, hidden // 2],
                [E, hidden, inter // 2],
                [token, topk],
            ],
            "Input type": [
                "c10::BFloat16",
                "c10::Float4_e2m1fn_x2",
                "c10::Float4_e2m1fn_x2",
                "float",
            ],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }


# ---------------------------------------------------------------------------
# GEMM and MoE
# ---------------------------------------------------------------------------
@register(
    "gemm_a8w8_blockscale",
    category="gemm",
    description="FP8 block-scaled GEMM (aiter CK)",
    model=(PERF_MODEL_EXT, "gemm_a8w8_blockscale"),
    defaults={"M": 2048, "N": 4096, "K": 8192},
    trace_names=(
        "aiter::gemm_a8w8_blockscale_ck",
        "aiter::gemm_a8w8_blockscale_cktile",
        "aiter::gemm_a8w8_blockscale_bpreshuffle_ck",
        "aiter::gemm_a8w8_blockscale_bpreshuffle_cktile",
        "aiter::flatmm_a8w8_blockscale_asm",
        "aiter::gfx950_a8w8_blockscale_asm",
        "aiter::gemm_a8w8_ck",
        "aiter::gemm_a8w8_bpreshuffle_ck",
        "sglang_profiler::fp8_utils_gemm_a8w8_blockscale_7",
    ),
)
def _gemm_a8w8_blockscale_event(args):
    """Event for ``aiter::gemm_a8w8_blockscale_ck`` (FP8 / INT8 block-scaled GEMM).

    Dtype kwargs read from ``args`` (defaults match
    :func:`tests.gemm.test_gemm_a8w8_blockscale`):

    * ``in_dtype`` -- activation storage (``"i8"``, ``"u8"``, ``"fp8"`` -- all 1 BPE).
    * ``w_dtype``  -- weight storage (``"i8"``, ``"u8"``, ``"fp8"`` -- all 1 BPE).
    * ``scale_dtype`` -- block-scale dtype (``"fp32"``).
    * ``block_k`` -- per-K-block tile size for scales (default 128).

    ``out_dtype`` is accepted for symmetry but the perf-model class hardcodes
    BF16 output (see ``perf_model_extensions.py:gemm_a8w8_blockscale``); it is
    forwarded to the test runner only.
    """
    return _a8w8_blockscale_event("aiter::gemm_a8w8_blockscale_ck", args)


@register(
    "gemm_a16w16_atomic_",
    category="gemm",
    description="BF16 GEMM (aiter ASM, atomic accumulation)",
    model=(PERF_MODEL_EXT, "gemm_a16w16_atomic_"),
    defaults={"M": 2048, "N": 4096, "K": 8192},
    trace_names=("aiter::gemm_a16w16_atomic_", "aiter::gemm_a16w16"),
)
def _gemm_a16w16_atomic__event(args):
    """Event for ``aiter::gemm_a16w16_atomic_`` (BF16 / FP16 GEMM).

    Dtype kwargs (``in_dtype`` / ``w_dtype`` / ``out_dtype``); kernel requires
    all three to match. Defaults to ``"bf16"``.
    """
    K = args.K
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::BFloat16")
    out_t = _dtype_from_args(args, "out_dtype", "c10::BFloat16")
    event = {
        "name": "aiter::gemm_a16w16_atomic_",
        "args": {
            "Input Dims": [[M, K], [N, K], [], [M, N]],
            "Input type": [in_t, w_t, "", out_t],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }
    return event


@register(
    "fmoe_fp8_blockscale_g1u1",
    category="moe",
    description="Fused FP8 block-scale MoE (g1u1 SwiGLU)",
    model=(MOE_EXT, "moe_aiter_fused_blockscale"),
    defaults={"M": 512, "N": 2048, "K": 7168, "E": 8, "topk": 2},
    trace_names=("aiter::fmoe_fp8_blockscale_g1u1",),
    csv_harness=True,
)
def _fmoe_fp8_blockscale_g1u1_event(args):
    """Event for ``aiter::fmoe_fp8_blockscale_g1u1``.

    Dtype kwargs read from ``args`` (all optional; defaults match
    :func:`tests.moe.test_fmoe_fp8_blockscale_g1u1`):

    * ``in_dtype``    -- activation dtype. ``"bf16"`` exercises the in-kernel
      quant path; ``"fp8"`` does caller-side ``pertoken_quant``. Default ``"bf16"``.
    * ``w_dtype``     -- expert weight dtype. Kernel only supports ``"fp8"``.
    * ``out_dtype``   -- output buffer dtype. Kernel only supports ``"bf16"``.
    * ``block_n`` / ``block_k`` -- block-scale tile sizes (default ``128``).
    """
    M, K, N, E, topk = (args.M, args.K, args.N, args.E, args.topk)
    in_t, w_t, out_t = _moe_dtypes_from_args(
        args, defaults=("c10::BFloat16", "c10::Float8_e4m3fnuz", "c10::BFloat16")
    )
    block_n = getattr(args, "block_n", None) or 128
    block_k = getattr(args, "block_k", None) or 128
    concrete = [None] * 15
    concrete[8] = topk
    concrete[13] = block_n
    concrete[14] = block_k
    event = {
        "name": "aiter::fmoe_fp8_blockscale_g1u1",
        "args": {
            "Input Dims": [[M, K], [M, K], [E, N * 2, K], [E, K, N]],
            "Input type": [out_t, in_t, w_t, w_t],
            "Concrete Inputs": concrete,
        },
    }
    return event


@register(
    "moe_cktile2stages_gemm1_ck",
    category="moe",
    description="CKTile MoE stage-1 GEMM (up projection)",
    model=(MOE_EXT, "moe_aiter_unfused_up"),
    defaults={"M": 512, "N": 2048, "K": 7168, "E": 8, "topk": 2},
    trace_names=("aiter::moe_cktile2stages_gemm1_ck",),
    csv_harness=True,
)
def _moe_cktile2stages_gemm1_ck_event(args):
    """Event for ``aiter::moe_cktile2stages_gemm1_ck`` (CK-Tile MoE up).

    Dtype kwargs (defaults reflect the BF16 / FP4-weight a16w4 path used by
    the unparameterized harness):

    * ``in_dtype``   -- activation dtype (default ``"bf16"``).
    * ``w_dtype``    -- packed FP4 weight dtype (default ``"fp4x2"``).
    * ``out_dtype``  -- output dtype (default ``"bf16"``).
    """
    M, K, N, E, topk = (args.M, args.K, args.N, args.E, args.topk)
    in_t, w_t, out_t = _moe_dtypes_from_args(
        args, defaults=("c10::BFloat16", "c10::Float4_e2m1fn_x2", "c10::BFloat16")
    )
    event = {
        "name": "aiter::moe_cktile2stages_gemm1_ck",
        "args": {
            "Input Dims": [[M, K], [E, N * 2, K], [M, topk, N]],
            "Input type": [in_t, w_t, out_t],
        },
    }
    return event


@register(
    "moe_cktile2stages_gemm2_ck",
    category="moe",
    description="CKTile MoE stage-2 GEMM (down projection)",
    model=(MOE_EXT, "moe_aiter_unfused_down"),
    defaults={"M": 512, "N": 2048, "K": 7168, "E": 8, "topk": 2},
    trace_names=("aiter::moe_cktile2stages_gemm2_ck",),
    csv_harness=True,
)
def _moe_cktile2stages_gemm2_ck_event(args):
    """Event for ``aiter::moe_cktile2stages_gemm2_ck`` (CK-Tile MoE down).

    Same dtype kwargs as ``moe_cktile2stages_gemm1_ck``.
    """
    M, K, N, E, topk = (args.M, args.K, args.N, args.E, args.topk)
    in_t, w_t, out_t = _moe_dtypes_from_args(
        args, defaults=("c10::BFloat16", "c10::Float4_e2m1fn_x2", "c10::BFloat16")
    )
    event = {
        "name": "aiter::moe_cktile2stages_gemm2_ck",
        "args": {
            "Input Dims": [[M, topk, N], [E, K, N], [M, K]],
            "Input type": [in_t, w_t, out_t],
        },
    }
    return event


@register(
    "ck_moe_stage1",
    category="moe",
    description="CK MoE stage-1 (up projection, fused activation)",
    model=(MOE_EXT, "moe_aiter_ck_stage1"),
    defaults={"M": 512, "N": 2048, "K": 7168, "E": 8, "topk": 2},
    trace_names=("aiter::ck_moe_stage1",),
    csv_harness=True,
)
def _ck_moe_stage1_event(args):
    """Event for ``aiter::ck_moe_stage1`` (CK MoE up + fused activation).

    Dtype kwargs:

    * ``in_dtype``   -- activation dtype. ``"bf16"``/``"fp16"`` (No quant) or
      ``"fp8"``/``"i8"``/``"fp4x2"`` (quantized A). Default ``"bf16"``.
    * ``w_dtype``    -- weight dtype (``"bf16"``/``"fp16"``/``"fp8"``/``"i8"``/
      ``"fp4x2"``). Default ``"bf16"``.
    * ``out_dtype``  -- output dtype (``"bf16"`` / ``"fp16"``). Default
      ``"bf16"``.
    """
    M, K, N, E, topk = (args.M, args.K, args.N, args.E, args.topk)
    in_t, w_t, out_t = _moe_dtypes_from_args(
        args, defaults=("c10::BFloat16", "c10::BFloat16", "c10::BFloat16")
    )
    event = {
        "name": "aiter::ck_moe_stage1",
        "args": {
            "Input Dims": [
                [M, K],
                [E, N * 2, K],
                [E, K, N],
                [M * topk],
                [E],
                [E],
                [M, topk, N],
            ],
            "Input type": [in_t, w_t, out_t],
        },
    }
    return event


@register(
    "ck_moe_stage2",
    category="moe",
    description="CK MoE stage-2 (down projection)",
    model=(MOE_EXT, "moe_aiter_ck_stage2"),
    defaults={"M": 512, "N": 2048, "K": 7168, "E": 8, "topk": 2},
    trace_names=("aiter::ck_moe_stage2",),
    csv_harness=True,
)
def _ck_moe_stage2_event(args):
    """Event for ``aiter::ck_moe_stage2`` (CK MoE down + topk reduce).

    Same dtype kwargs as ``ck_moe_stage1``.
    """
    M, K, N, E, topk = (args.M, args.K, args.N, args.E, args.topk)
    in_t, w_t, out_t = _moe_dtypes_from_args(
        args, defaults=("c10::BFloat16", "c10::BFloat16", "c10::BFloat16")
    )
    event = {
        "name": "aiter::ck_moe_stage2",
        "args": {
            "Input Dims": [
                [M, topk, N],
                [E, N * 2, K],
                [E, K, N],
                [M * topk],
                [E],
                [E],
                [M, K],
            ],
            "Input type": [in_t, w_t, out_t],
        },
    }
    return event


# Qwen3-30B-A3B gate/up shape: hidden=2048, 2*inter=1536, E=128, topk=8.
@register(
    "sglang_fused_moe_triton_invoke",
    category="moe",
    description="SGLang Triton fused-MoE grouped GEMM (invoke_fused_moe_kernel)",
    model=(MOE_EXT, "moe_triton_invoke_grouped_gemm"),
    defaults={"M": 15360, "N": 1536, "K": 2048, "E": 128, "topk": 8},
    trace_names=(
        "sglang_profiler::fused_moe_triton_kernels_invoke_fused_moe_kernel",
        "sglang_profiler::fused_moe_triton_kernels_invoke_fused_moe_kernel_427",
    ),
)
def _sglang_fused_moe_triton_invoke_event(args):
    """Event for ``sglang_profiler::fused_moe_triton_kernels_invoke_fused_moe_kernel``.

    A single SGLang Triton ``invoke_fused_moe_kernel`` launch (one grouped GEMM).
    This same op name covers both the gate/up and the down projection; the
    perf-model class derives ``(M_work, N, K)`` generically from the args, so a
    single representative shape validates either direction.

    Args read:

    * ``M``     -- number of input tokens (pre-expansion).
    * ``N``     -- weight output dim (for gate/up pass this is ``2*inter_dim``).
    * ``K``     -- weight contraction dim (hidden_dim for gate/up).
    * ``E``     -- number of experts.
    * ``topk``  -- experts per token.
    * ``in_dtype``  -- activation dtype (default ``"bf16"``; quantized to fp8 in-kernel).
    * ``w_dtype``   -- expert weight dtype (default ``"fp8"``).
    * ``out_dtype`` -- output dtype (default ``"bf16"``).

    The event layout mirrors the trace ``Input Dims``:
        [0] A            = (M, K)
        [1] B            = (E, N, K)
        [2] C            = ()                (output, dims unrecorded)
        [3] C buffer     = (M*topk, N)
        [4] ()
        [5] B_scale      = (E,)
        [6] ()
        [7] topk_weights = (M, topk)
        [8] topk_ids     = (M, topk)
    """
    M, K, N, E, topk = (args.M, args.K, args.N, args.E, args.topk)
    in_t, w_t, out_t = _moe_dtypes_from_args(
        args, defaults=("c10::BFloat16", "c10::Float8_e4m3fnuz", "c10::BFloat16")
    )
    event = {
        "name": "sglang_profiler::fused_moe_triton_kernels_invoke_fused_moe_kernel",
        "args": {
            "Input Dims": [
                [M, K],
                [E, N, K],
                [],
                [M * topk, N],
                [],
                [E],
                [],
                [M, topk],
                [M, topk],
                [M * topk + E * 64],
                [E * 2],
                [1],
                [],
            ],
            "Input type": [
                in_t,
                w_t,
                "",
                out_t,
                "",
                "float",
                "",
                "float",
                "int",
                "int",
                "int",
                "int",
                "",
            ],
        },
    }
    return event


# ---------------------------------------------------------------------------
# Gated activations
# ---------------------------------------------------------------------------
for _fn_name, _description, _trace_names in _ACTIVATION_OPS:
    register(
        _fn_name,
        category="activation",
        description=_description,
        model=(PERF_MODEL_EXT, f"aiter_{_fn_name}"),
        defaults={"M": 2048, "N": 7168},
        trace_names=_trace_names,
    )(functools.partial(_activation_event, _fn_name))


# ---------------------------------------------------------------------------
# Norm and quant
# ---------------------------------------------------------------------------
@register(
    "rms_norm",
    category="norm",
    description="RMSNorm (CK, aiter::rms_norm)",
    model=(RMSNORM_EXT, "aiter_rms_norm"),
    defaults={"M": 2048, "N": 7168},
    trace_names=("aiter::rms_norm", "aiter::rmsnorm2d_fwd_ck"),
)
def _rms_norm_event(args):
    """Event for ``aiter::rms_norm`` (CK).

    Reads ``in_dtype`` (slot ``[0]``), ``w_dtype`` (slot ``[1]``). Output
    traffic is computed using ``in_dtype`` (kernel out matches input).
    Defaults match :func:`tests.rmsnorm.test_rms_norm`.
    """
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::BFloat16")
    event = {
        "name": "aiter::rms_norm",
        "args": {
            "Input Dims": [[M, N], [N], [], []],
            "Input type": [in_t, w_t, "Scalar", "Scalar"],
            "Input Strides": [[N, 1], [1], [], []],
        },
    }
    return event


@register(
    "rmsnorm",
    category="norm",
    description="RMSNorm (aiter::rmsnorm, out-first API)",
    model=(RMSNORM_EXT, "aiter_rmsnorm"),
    defaults={"M": 2048, "N": 7168},
    trace_names=("aiter::rmsnorm",),
)
def _rmsnorm_event(args):
    """Event for ``aiter::rmsnorm`` (out-first API).

    Note that the perf model class reads slot ``[1]`` for the input dtype
    (the API is ``rmsnorm(out, inp, weight, eps)`` so slot ``[0]`` is the
    out buffer). Both slots therefore receive ``in_dtype``; ``w_dtype`` goes
    to slot ``[2]``.
    """
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::BFloat16")
    out_t = _dtype_from_args(args, "out_dtype", in_t)
    event = {
        "name": "aiter::rmsnorm",
        "args": {
            "Input Dims": [[M, N], [M, N], [N], []],
            "Input type": [out_t, in_t, w_t, "Scalar"],
            "Input Strides": [[N, 1], [N, 1], [1], []],
        },
    }
    return event


@register(
    "add_rmsnorm",
    category="norm",
    description="Fused residual-add + RMSNorm",
    model=(RMSNORM_EXT, "aiter_rmsnorm2d_fwd_with_add_ck"),
    defaults={"M": 2048, "N": 7168},
    trace_names=("aiter::add_rmsnorm", "aiter::rmsnorm2d_fwd_with_add_ck"),
)
def _add_rmsnorm_event(args):
    """Event for ``aiter::add_rmsnorm`` (fused residual-add + RMSNorm).

    Slot ``[1]`` is the input (read by the perf-model class for byte-counting
    and compute precision). All BF16 traffic uses ``in_dtype``.
    """
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::BFloat16")
    event = {
        "name": "aiter::add_rmsnorm",
        "args": {
            "Input Dims": [[M, N], [M, N], [M, N], [M, N], [N], [], []],
            "Input type": [in_t, in_t, in_t, in_t, w_t, "Scalar", "Scalar"],
            "Input Strides": [[N, 1], [N, 1], [N, 1], [N, 1], [1], [], []],
        },
    }
    return event


@register(
    "rmsnorm_dynamicquant",
    category="norm",
    description="Fused RMSNorm + dynamic FP8 quantization",
    model=(RMSNORM_EXT, "aiter_rmsnorm2d_fwd_with_dynamicquant_ck"),
    defaults={"M": 2048, "N": 7168},
    trace_names=("aiter::rmsnorm2d_fwd_with_dynamicquant_ck",),
)
def _rmsnorm_dynamicquant_event(args):
    """Event for ``aiter::rmsnorm2d_fwd_with_dynamicquant_ck``.

    Reads slot ``[1]`` for the input dtype. FP8 output bytes (slot ``[0]``)
    and per-token FP32 scale bytes (slot ``[2]``) are hardcoded by the
    perf-model class, so changing ``out_dtype`` only affects the test runner
    side.
    """
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::BFloat16")
    out_t = _dtype_from_args(args, "out_dtype", "unsigned char")
    scl_t = _dtype_from_args(args, "scale_dtype", "float")
    event = {
        "name": "aiter::rmsnorm2d_fwd_with_dynamicquant_ck",
        "args": {
            "Input Dims": [[M, N], [M, N], [M, 1], [N], [], []],
            "Input type": [out_t, in_t, scl_t, w_t, "Scalar", "Scalar"],
            "Input Strides": [[N, 1], [N, 1], [1, 1], [1], [], []],
        },
    }
    return event


@register(
    "dynamic_per_token_scaled_quant",
    category="quant",
    description="Dynamic per-token FP8 quantization",
    model=(PERF_MODEL_EXT, "per_group_quant"),
    defaults={"M": 2048, "N": 7168},
    trace_names=("aiter::dynamic_per_token_scaled_quant",),
)
def _dynamic_per_token_scaled_quant_event(args):
    """Event for ``aiter::dynamic_per_token_scaled_quant``.

    Reads slot ``[0]`` for output dtype, slot ``[1]`` for input, slot ``[2]``
    for scales. Compute precision is taken from input.
    """
    N = args.N
    M = args.M
    out_t = _dtype_from_args(args, "out_dtype", "c10::Float8_e4m3fnuz")
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    scl_t = _dtype_from_args(args, "scale_dtype", "float")
    event = {
        "name": "aiter::dynamic_per_token_scaled_quant",
        "args": {
            "Input Dims": [[M, N], [M, N], [M, 1]],
            "Input type": [out_t, in_t, scl_t],
            "Input Strides": [[N, 1], [N, 1], [1, 1]],
        },
    }
    return event


# ---------------------------------------------------------------------------
# Attention
# ---------------------------------------------------------------------------
@register(
    "_flash_attn_forward",
    category="attention",
    description="Flash Attention forward (CK)",
    model=(PERF_MODEL, "aiter__flash_attn_forward"),
    defaults={"seq_len": 2048, "num_heads_q": 32, "num_heads_kv": 8, "head_dim": 128},
    trace_names=("aiter::_flash_attn_forward",),
)
def _flash_attn_forward_event(args):
    """Event for ``aiter::_flash_attn_forward`` (CK flash attention).

    Reads ``in_dtype`` for Q/K/V slots (kernel requires matching dtypes).

    Note
    ----
    The upstream perf-model class (``aiter__flash_attn_forward``) hardcodes
    ``bytes_per_element=2`` in its ``bytes()`` method, so changing
    ``in_dtype`` does not affect predicted bytes; it only flows through to
    the test runner. ``get_compute_precision()`` returns ``None`` for this
    class (it never populates ``param_details["dtype_A_B"]``).
    """
    S = args.seq_len
    d = args.head_dim
    H_KV = args.num_heads_kv
    H_Q = args.num_heads_q
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    concrete = [""] * 12
    concrete[3] = "0.0"
    concrete[5] = "true"
    event = {
        "name": "aiter::_flash_attn_forward",
        "args": {
            "Input Dims": [[1, S, H_Q, d], [1, S, H_KV, d], [1, S, H_KV, d]],
            "Input type": [in_t, in_t, in_t],
            "Concrete Inputs": concrete,
        },
    }
    return event


@register(
    "wrapper_fmha_v3_fwd",
    category="attention",
    description="FMHA v3 forward",
    model=(PERF_MODEL, "aiter__fmha_v3_forward"),
    defaults={"seq_len": 2048, "num_heads_q": 32, "num_heads_kv": 8, "head_dim": 128},
    trace_names=("aiter::wrapper_fmha_v3_fwd",),
    csv_harness=True,
)
def _wrapper_fmha_v3_fwd_event(args):
    """Event for ``aiter::wrapper_fmha_v3_fwd`` (FMHA v3 dense forward).

    Same dtype constraints + same hardcoded-bytes caveat as
    ``_flash_attn_forward``.
    """
    S = args.seq_len
    d = args.head_dim
    H_KV = args.num_heads_kv
    H_Q = args.num_heads_q
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    concrete = [""] * 9
    concrete[4] = "0.0"
    concrete[6] = "true"
    event = {
        "name": "aiter::wrapper_fmha_v3_fwd",
        "args": {
            "Input Dims": [[], [1, S, H_Q, d], [1, S, H_KV, d], [1, S, H_KV, d]],
            "Input type": ["", in_t, in_t, in_t],
            "Concrete Inputs": concrete,
        },
    }
    return event


@register(
    "mha_varlen_fwd",
    category="attention",
    description="MHA variable-length forward (CK)",
    model=(ATTN_EXT, "mha_varlen_fwd"),
    defaults={"seq_len": 2048, "num_heads_q": 32, "num_heads_kv": 8, "head_dim": 128},
    trace_names=("aiter::mha_varlen_fwd",),
    csv_harness=True,
)
def _mha_varlen_fwd_event(args):
    """Event for ``aiter::mha_varlen_fwd`` (CK varlen flash attention).

    Reads slot ``[0]`` for Q dtype. Bytes are computed as
    ``name2bpe(dtype_Q) or 2``, so passing ``--in_dtype fp16`` yields BF16
    -> FP16 byte counts (both 2 BPE) and equivalent compute precision.

    Annotation format
    -----------------
    Uses the canonical ``execute_*`` format shared by all attention harnesses::

        execute_0_context_N(sq<c_sq>sk<c_sk>sqsq<c_sqsq>sqsk<c_sqsk>)
                            _generation_0(sq0sk0sqsq0sqsk0)

    where:

    * ``c_sq``  = total Q tokens across all context sequences
    * ``c_sk``  = total KV tokens across all context sequences (= ``total_kv``)
    * ``c_sqsq``= Σ sq_i²  (causal correction)
    * ``c_sqsk``= Σ sq_i·sk_i  (= c_sqsq for self-attention where sq_i = sk_i)

    The generation block is always zero because this is a prefill-only kernel.
    """
    d = args.head_dim
    H_KV = args.num_heads_kv
    H_Q = args.num_heads_q
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    annotation, total_q, total_kv = _varlen_annotation(args)
    event = {
        "name": "aiter::mha_varlen_fwd",
        "annotation": annotation,
        "args": {
            "Input Dims": [[total_q, H_Q, d], [total_kv, H_KV, d]],
            "Input type": [in_t, in_t],
        },
    }
    return event


@register(
    "fmha_v3_varlen_fwd",
    category="attention",
    description="FMHA v3 variable-length forward",
    model=(ATTN_EXT, "aiter_fmha_v3_varlen_fwd"),
    defaults={"seq_len": 2048, "num_heads_q": 32, "num_heads_kv": 8, "head_dim": 128},
    trace_names=("aiter::fmha_v3_varlen_fwd",),
    csv_harness=True,
)
def _fmha_v3_varlen_fwd_event(args):
    """Event for ``aiter::fmha_v3_varlen_fwd`` (FMHA v3 varlen forward).

    Same dtype + annotation semantics as ``mha_varlen_fwd``:
    uses the canonical ``execute_*`` format with a zero-generation block.
    """
    d = args.head_dim
    H_KV = args.num_heads_kv
    H_Q = args.num_heads_q
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    annotation, total_q, total_kv = _varlen_annotation(args)
    event = {
        "name": "aiter::fmha_v3_varlen_fwd",
        "annotation": annotation,
        "args": {
            "Input Dims": [[total_q, H_Q, d], [total_kv, H_KV, d], [total_kv, H_KV, d]],
            "Input type": [in_t, in_t, in_t],
        },
    }
    return event


# ---------------------------------------------------------------------------
# vLLM ops
# ---------------------------------------------------------------------------
@register(
    "vllm_unquantized_gemm",
    category="vllm_gemm",
    description="vLLM BF16 GEMM (rocm_unquantized_gemm)",
    model=(PERF_MODEL_EXT, "vllm_rocm_unquantized_gemm"),
    defaults={"M": 2048, "N": 4096, "K": 8192},
    trace_names=("vllm::rocm_unquantized_gemm",),
)
def _vllm_unquantized_gemm_event(args):
    """Event for ``vllm::rocm_unquantized_gemm`` (BF16 / FP16 GEMM).

    Dtype kwargs (defaults match :func:`tests.gemm.test_vllm_unquantized_gemm`):

    * ``in_dtype`` / ``w_dtype`` -- activation / weight (default ``"bf16"``).
    * ``bias_dtype`` -- bias dtype if a bias is supplied (default unset =
      no bias). Set this to enable the bias-traffic bytes term.
    """
    K = args.K
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::BFloat16")
    bias_t = _dtype_from_args(args, "bias_dtype", "")
    event = {
        "name": "vllm::rocm_unquantized_gemm",
        "args": {
            "Input Dims": [[M, K], [N, K]],
            "Input type": [in_t, w_t, bias_t],
            "Input Strides": [[K, 1], [K, 1]],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }
    return event


@register(
    "vllm_triton_gemm_a8w8_blockscale",
    category="vllm_gemm",
    description="vLLM FP8 block-scaled GEMM (wraps aiter gemm_a8w8_blockscale)",
    model=(PERF_MODEL_EXT, "gemm_a8w8_blockscale"),
    defaults={"M": 2048, "N": 4096, "K": 8192},
    trace_names=("vllm::rocm_aiter_triton_gemm_a8w8_blockscale",),
)
def _vllm_triton_gemm_a8w8_blockscale_event(args):
    """Event for the vLLM Triton wrapper around ``gemm_a8w8_blockscale``.

    Same dtype semantics as ``gemm_a8w8_blockscale``.
    """
    return _a8w8_blockscale_event("vllm::rocm_aiter_triton_gemm_a8w8_blockscale", args)


@register(
    "vllm_gemm_with_dynamic_quant",
    category="vllm_gemm",
    description="vLLM FP4 GEMM with dynamic quantization (Quark OCP MX)",
    model=(PERF_MODEL, "vllm_gemm_with_dynamic_quant"),
    defaults={"M": 2048, "N": 4096, "K": 8192},
    trace_names=("vllm::gemm_with_dynamic_quant",),
    csv_harness=True,
)
def _vllm_gemm_with_dynamic_quant_event(args):
    """Event for ``vllm::gemm_with_dynamic_quant`` (Quark OCP MX FP4 GEMM).

    Dtype kwargs:

    * ``in_dtype`` -- activation dtype (``"bf16"`` / ``"fp16"``). The perf
      model uses this for both the activation traffic AND the output traffic
      (the class only reads slot ``[0]``).
    * ``w_dtype`` -- weight dtype (``"fp4x2"``, default). Forwarded to the
      test runner; perf-model bytes for the weight is computed implicitly
      from ``in_dtype`` (limitation of the upstream class).
    * ``scale_dtype`` -- per-32 OCP MX scale dtype (default ``"u8"``).
    """
    K = args.K
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "unsigned char")
    scl_t = _dtype_from_args(args, "scale_dtype", "unsigned char")
    event = {
        "name": "vllm::gemm_with_dynamic_quant",
        "args": {
            "Input Dims": [[M, K], [N, K // 2], [N, K // 32]],
            "Input type": [in_t, w_t, scl_t],
            "Input Strides": [[K, 1], [K // 2, 1], [K // 32, 1]],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }
    return event


@register(
    "vllm_triton_group_quant_fp8",
    category="vllm_quant",
    description="vLLM Triton FP8 per-group quantization",
    model=(PERF_MODEL_EXT, "vllm_triton_per_token_group_quant_fp8"),
    defaults={"M": 2048, "N": 7168, "group_size": 128},
    required_args=["M", "N"],
    trace_names=("vllm::triton_per_token_group_quant_fp8",),
)
def _vllm_triton_group_quant_fp8_event(args):
    """Event for ``vllm::triton_per_token_group_quant_fp8``.

    Reads slot ``[0]`` for input dtype. FP8 output (1 BPE) and FP32 scales
    (4 BPE) are hardcoded by the upstream class.
    """
    N = args.N
    M = args.M
    group_size = getattr(args, "group_size", None) or 128
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    event = {
        "name": "vllm::triton_per_token_group_quant_fp8",
        "args": {
            "Input Dims": [(M, N), ()],
            "Input type": [in_t, "Scalar"],
            "Concrete Inputs": ["", str(group_size)],
        },
    }
    return event


@register(
    "vllm_rmsnorm_fp8_group_quant",
    category="vllm_norm",
    description="vLLM fused RMSNorm + FP8 group quantization",
    model=(RMSNORM_EXT, "vllm_rocm_aiter_rmsnorm_fp8_group_quant"),
    defaults={"M": 2048, "N": 7168, "group_size": 128},
    required_args=["M", "N"],
    trace_names=("vllm::rocm_aiter_rmsnorm_fp8_group_quant",),
)
def _vllm_rmsnorm_fp8_group_quant_event(args):
    """Event for ``vllm::rocm_aiter_rmsnorm_fp8_group_quant``.

    Reads slot ``[0]`` for x dtype (input). The FP8 quant output and FP32
    scales are hardcoded by the upstream class.
    """
    N = args.N
    M = args.M
    group_size = getattr(args, "group_size", None) or 128
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::BFloat16")
    event = {
        "name": "vllm::rocm_aiter_rmsnorm_fp8_group_quant",
        "args": {
            "Input Dims": [(M, N), (N,), (), ()],
            "Input type": [in_t, w_t, "Scalar", "Scalar"],
            "Input Strides": [(N, 1), (1,), (), ()],
            "Concrete Inputs": ["", "", "", str(group_size)],
        },
    }
    return event


@register(
    "vllm_rmsnorm_add_fp8_group_quant",
    category="vllm_norm",
    description="vLLM fused residual-add + RMSNorm + FP8 group quantization",
    model=(RMSNORM_EXT, "vllm_rocm_aiter_rmsnorm_with_add_fp8_group_quant"),
    defaults={"M": 2048, "N": 7168, "group_size": 128},
    required_args=["M", "N"],
    trace_names=("vllm::rocm_aiter_rmsnorm_with_add_fp8_group_quant",),
)
def _vllm_rmsnorm_add_fp8_group_quant_event(args):
    """Event for ``vllm::rocm_aiter_rmsnorm_with_add_fp8_group_quant``."""
    N = args.N
    M = args.M
    group_size = getattr(args, "group_size", None) or 128
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::BFloat16")
    event = {
        "name": "vllm::rocm_aiter_rmsnorm_with_add_fp8_group_quant",
        "args": {
            "Input Dims": [(M, N), (M, N), (N,), (), ()],
            "Input type": [in_t, in_t, w_t, "Scalar", "Scalar"],
            "Input Strides": [(N, 1), (N, 1), (1,), (), ()],
            "Concrete Inputs": ["", "", "", "", str(group_size)],
        },
    }
    return event


@register(
    "vllm_unified_attention",
    category="vllm_attention",
    description="vLLM unified attention (paged decode via aiter.paged_attention_v1, FP8 KV cache)",
    model=(ATTN_EXT, "vllm_unified_attention_with_output"),
    defaults={"seq_len": 2048, "num_heads_q": 32, "num_heads_kv": 8, "head_dim": 128},
    trace_names=("vllm::unified_attention_with_output",),
    csv_harness=True,
)
def _vllm_unified_attention_event(args):
    """Event for ``vllm::unified_attention_with_output`` (paged decode).

    Reads slot ``[0]`` for Q dtype (via ``InferenceAttention.get_param_details``).
    The KV-cache dtype is conveyed via slot ``[1]`` for documentation, even
    though the upstream class does not consume it -- bytes are
    ``name2bpe(dtype_Q) or 2``.

    Annotation flow
    ---------------
    All scenarios converge on a canonical vLLM-format annotation:

        execute_<iter>_context_<c_n>(sq<c_sq>sk<c_sk>sqsq<c_sqsq>sqsk<c_sqsk>)
                      _generation_<g_n>(sq<g_sq>sk<g_sk>sqsq<g_sqsq>sqsk<g_sqsk>)

    ``vllm_unified_attention_with_output`` is a paged-decode-only kernel; any
    prefill in the same scheduler step runs through a separate flash-attention
    kernel.  Therefore c_* are always 0 here and all decode statistics live in
    the g_* fields:

        g_sq   = n_decode              (one Q token per decode sequence)
        g_sk   = n_decode * ctx_len    (total KV tokens accessed by the kernel)
        g_sqsq = g_sq  (same; no causal masking across sequences)
        g_sqsk = g_sk  (same)

    ``sum_q`` and ``sum_kv`` are then derived by parsing this annotation through
    ``_parse_unified_attention_annotation``, matching the identical path used for
    real vLLM traces.  This ensures the perf model's FLOPs and bytes calculations
    are consistent regardless of the annotation source.
    """
    return _build_unified_attention_event("vllm::unified_attention_with_output", args)


@register(
    "unified_attention",
    category="attention",
    description="aiter triton unified_attention (paged KV / varlen, accepts --annotation)",
    model=(ATTN_EXT, "vllm_unified_attention_with_output"),
    defaults={"seq_len": 2048, "num_heads_q": 32, "num_heads_kv": 8, "head_dim": 128},
    trace_names=("aiter::unified_attention",),
    csv_harness=True,
)
def _unified_attention_event(args):
    """Event for aiter triton ``unified_attention`` (paged KV / varlen).

    Reuses ``vllm_unified_attention_with_output`` (same kernel under the hood).

    Annotation flow
    ---------------
    Identical to ``vllm_unified_attention``: all scenarios
    converge on the canonical ``execute_*`` format::

        execute_<iter>_context_<c_n>(sq<c_sq>sk<c_sk>sqsq<c_sqsq>sqsk<c_sqsk>)
                      _generation_<g_n>(sq<g_sq>sk<g_sk>sqsq<g_sqsq>sqsk<g_sqsk>)

    If ``args.annotation`` already carries a valid ``execute_*`` string it is
    passed through verbatim.  Otherwise a synthetic annotation is built from
    ``args.num_decode_seqs`` / ``args.ctx_len`` / ``args.prefill_seq_len``
    (falling back to ``args.seq_len`` as a single-sequence decode scenario).

    Dtype kwargs ``in_dtype`` / ``kv_dtype`` mirror
    ``vllm_unified_attention``.
    """
    return _build_unified_attention_event("aiter::unified_attention", args)


@register(
    "vllm_gdn_attention_core",
    category="vllm_attention",
    description="vLLM Gated Delta Network attention (perf-model-only)",
    model=(ATTN_EXT, "gdn_attention_core"),
    defaults={"seq_len": 2048, "num_heads_kv": 16, "head_dim": 128},
    trace_names=("vllm::gdn_attention_core",),
    csv_harness=True,
    perf_model_only=True,
)
def _vllm_gdn_attention_core_event(args):
    """Event for ``vllm::gdn_attention_core`` (Gated Delta Network).

    Reads slot ``[0]`` for compute precision (mixed_qkv dtype). The ``bytes()``
    method hardcodes 2 BPE so changing dtype only affects the test runner
    side.
    """
    return _gdn_event(
        "vllm::gdn_attention_core",
        args,
        H_K=args.num_heads_kv // 2,
        annotation=f"attn_0_0_{args.seq_len}_{args.seq_len * args.seq_len}_0_0_0",
    )


# ---------------------------------------------------------------------------
# DSV3 triage-extension ops (perf models in the file named by
# DSV3_TRIAGE_EXTENSION)
# ---------------------------------------------------------------------------
@register(
    "dsv3_flydsl_hgemm",
    category="dsv3",
    description="AITER FlyDSL BF16 GEMM (sglang_profiler::gemm_kernels_flydsl_hgemm_54)",
    model=(DSV3_EXT, "sglang_flydsl_hgemm"),
    defaults={"M": 32, "N": 256, "K": 7168},
)
def _dsv3_flydsl_hgemm_event(args):
    """Event for ``sglang_profiler::gemm_kernels_flydsl_hgemm_54`` (BF16 GEMM)."""
    K = args.K
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    event = {
        "name": "sglang_profiler::gemm_kernels_flydsl_hgemm_54",
        "args": {
            "Input Dims": [[M, K], [N, K], [], []],
            "Input type": [in_t, in_t, "", ""],
            "Input Strides": [[K, 1], [K, 1], [], []],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }
    return event


@register(
    "dsv3_batched_gemm_a8w8",
    category="dsv3",
    description="AITER batched A8W8 GEMM (per-token-group prequant)",
    model=(DSV3_EXT, "sglang_batched_gemm_a8w8"),
    defaults={"M": 32, "N": 128, "K": 512, "E": 16, "group_size": 128},
    required_args=["M", "N", "K", "E"],
)
def _dsv3_batched_gemm_a8w8_event(args):
    """Event for sglang_profiler::batched_gemm_a8w8 (batched A8W8 GEMM)."""
    M, N, K, E = (args.M, args.N, args.K, args.E)
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    w_t = _dtype_from_args(args, "w_dtype", "c10::Float8_e4m3fn")
    scl_t = _dtype_from_args(args, "scale_dtype", "float")
    event = {
        "name": "sglang_profiler::batched_gemm_a8w8_a_per_token_group_prequant_w_per_batched_tensor_quant_batched_gemm_a8w8_a_per_token_group_prequant_w_per_batched_tensor_quant_558",
        "args": {
            "Input Dims": [[E, M, K], [E, N, K], [], [], []],
            "Input type": [in_t, w_t, scl_t, "", ""],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }
    return event


@register(
    "dsv3_fused_flatten_fp8_group_quant",
    category="dsv3",
    description="AITER triton fused flatten + FP8 group quant",
    model=(DSV3_EXT, "sglang_fused_flatten_fp8_group_quant"),
    defaults={"M": 32, "N": 2048, "group_size": 128},
    required_args=["M", "N"],
)
def _dsv3_fused_flatten_fp8_group_quant_event(args):
    """Event for sglang_profiler::quant_fused_flatten_fp8_group_quant_37."""
    N = args.N
    M = args.M
    group_size = getattr(args, "group_size", None) or 128
    if N % group_size != 0:
        raise ValueError(f"""N ({N}) must be divisible by group_size ({group_size})""")
    N2 = group_size
    N1 = N // group_size
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    event = {
        "name": "sglang_profiler::quant_fused_flatten_fp8_group_quant_37",
        "args": {
            "Input Dims": [[M, N1, N2]],
            "Input type": [in_t],
            "Input Strides": [[N, N2, 1]],
        },
    }
    return event


@register(
    "dsv3_fused_qk_rope_cat_and_cache_mla",
    category="dsv3",
    description="AITER triton fused QK RoPE + KV cache write (MLA)",
    model=(DSV3_EXT, "aiter_fused_qk_rope_cat_and_cache_mla"),
    defaults={"M": 32, "num_heads_q": 16, "head_dim": 576, "group_size": 64},
    required_args=["M"],
    trace_names=("aiter::fused_qk_rope_cat_and_cache_mla",),
)
def _dsv3_fused_qk_rope_cat_and_cache_mla_event(args):
    """Event for aiter::fused_qk_rope_cat_and_cache_mla."""
    T = args.M
    H_q = getattr(args, "num_heads_q", None) or 16
    head_dim = getattr(args, "head_dim", None) or 576
    D_pe = getattr(args, "group_size", None) or 64
    D_lora = head_dim - D_pe
    KH = 1
    num_kv_cache_tokens = max(T + 4096, 8192)
    max_pos = max(T * 16, 4096)
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    event = {
        "name": "aiter::fused_qk_rope_cat_and_cache_mla",
        "args": {
            "Input Dims": [
                [T, H_q, D_lora],
                [T, H_q, D_pe],
                [T, KH, D_lora],
                [T, KH, D_pe],
                [num_kv_cache_tokens, KH, D_lora + D_pe],
                [T],
                [T],
                [max_pos, 1, 1, D_pe // 2],
                [max_pos, 1, 1, D_pe // 2],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
            ],
            "Input type": [in_t] * 5
            + [
                "long int",
                "long int",
                in_t,
                in_t,
                "float",
                "Scalar",
                "Scalar",
                "Scalar",
                "",
                "",
                "",
                "Scalar",
            ],
            "Concrete Inputs": [""] * 10 + ["False", "0", "True", "", "", "", "0"],
        },
    }
    return event


# Routing/metadata op: needs valid sorted expert ids to run safely.
# Validate the perf model against the CSV-reported roofline only.
@register(
    "dsv3_fused_append_shared_experts",
    category="dsv3",
    description="sglang triton MoE fused-append-shared-experts",
    model=(DSV3_EXT, "sglang_fused_append_shared_experts"),
    defaults={"M": 32, "K": 8, "E": 256},
    required_args=["M"],
    trace_names=(
        "sglang_profiler::fused_moe_triton_kernels_fused_append_shared_experts",
    ),
    perf_model_only=True,
)
def _dsv3_fused_append_shared_experts_event(args):
    """Event for sglang_profiler::fused_moe_triton_kernels_fused_append_shared_experts_456."""
    M = args.M
    K = getattr(args, "K", None) or 8
    event = {
        "name": "sglang_profiler::fused_moe_triton_kernels_fused_append_shared_experts_456",
        "args": {"Input Dims": [[M, K], [M, K]], "Input type": ["int", "float"]},
    }
    return event


@register(
    "dsv3_dynamic_per_group_scaled_quant_fp4",
    category="dsv3",
    description="AITER dynamic per-group (x32) FP4 activation quant",
    model=(DSV3_EXT, "aiter_dynamic_per_group_scaled_quant_fp4"),
    defaults={"M": 64575, "N": 7168},
    trace_names=("aiter::dynamic_per_group_scaled_quant_fp4",),
)
def _dsv3_dynamic_per_group_scaled_quant_fp4_event(args):
    """Event for aiter::dynamic_per_group_scaled_quant_fp4."""
    M = args.M
    N = getattr(args, "N", None) or 7168
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    event = {
        "name": "aiter::dynamic_per_group_scaled_quant_fp4",
        "args": {
            "Input Dims": [[M, N // 2], [M, N], [M, N // 32]],
            "Input type": ["c10::Float4_e2m1fn_x2", in_t, "c10::Float8_e8m0fnu"],
        },
    }
    return event


@register(
    "dsv3_quant_dynamic_mxfp4_quant",
    category="dsv3",
    description="AITER dynamic MXFP4 activation quant (sglang quark w4a4)",
    model=(DSV3_EXT, "sglang_quant_dynamic_mxfp4_quant"),
    defaults={"M": 64, "N": 7168},
    trace_names=("sglang_profiler::quant_dynamic_mxfp4_quant",),
)
def _dsv3_quant_dynamic_mxfp4_quant_event(args):
    """Event for sglang_profiler::quant_dynamic_mxfp4_quant."""
    M = args.M
    N = getattr(args, "N", None) or 7168
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    event = {
        "name": "sglang_profiler::quant_dynamic_mxfp4_quant",
        "args": {"Input Dims": [[M, N]], "Input type": [in_t]},
    }
    return event


# Fused quant+sort needs valid sorted ids; validate perf model vs CSV.
@register(
    "dsv3_fused_dynamic_mxfp4_quant_moe_sort_hip",
    category="dsv3",
    description="AITER fused dynamic MXFP4 quant + MoE sort",
    model=(DSV3_EXT, "aiter_fused_dynamic_mxfp4_quant_moe_sort_hip"),
    defaults={"M": 64, "N": 7168},
    trace_names=("aiter::fused_dynamic_mxfp4_quant_moe_sort_hip",),
    perf_model_only=True,
)
def _dsv3_fused_dynamic_mxfp4_quant_moe_sort_hip_event(args):
    """Event for aiter::fused_dynamic_mxfp4_quant_moe_sort_hip."""
    M = args.M
    N = getattr(args, "N", None) or 7168
    in_t = _dtype_from_args(args, "in_dtype", "c10::BFloat16")
    event = {
        "name": "aiter::fused_dynamic_mxfp4_quant_moe_sort_hip",
        "args": {
            "Input Dims": [[M, N // 2], [8800, N // 32], [M, N], [8791], [2]],
            "Input type": [
                "c10::Float4_e2m1fn_x2",
                "c10::Float8_e8m0fnu",
                in_t,
                "int",
                "int",
            ],
        },
    }
    return event


@register(
    "dsv3_mla_prefill_ps_asm_fwd",
    category="dsv3",
    description="AITER ASM MLA prefill (persistent scheduler, FP8)",
    model=(DSV3_EXT, "aiter_mla_prefill_ps_asm_fwd"),
    defaults={
        "seq_len": 1024,
        "E": 16,
        "num_heads_q": 16,
        "head_dim": 192,
        "block_n": 1,
    },
    required_args=["seq_len"],
)
def _dsv3_mla_prefill_ps_asm_fwd_event(args):
    """Event for aiter::mla_prefill_ps_asm_fwd.

    Reads ``--seq_len`` (per-batch ctx), ``--E`` (batch size), ``--num_heads_q``,
    ``--head_dim`` (qk_head_dim; v_head_dim = head_dim - 64).
    """
    seq_len = args.seq_len
    batch = getattr(args, "E", None) or 16
    H = getattr(args, "num_heads_q", None) or 16
    d_qk = getattr(args, "head_dim", None) or 192
    d_v = d_qk - 64
    N_total = seq_len * batch
    in_t = _dtype_from_args(args, "in_dtype", "c10::Float8_e4m3fn")
    event = {
        "name": "aiter::mla_prefill_ps_asm_fwd",
        "args": {
            "Input Dims": [
                [N_total, H, d_qk],
                [N_total, H, d_qk],
                [N_total, H, d_v],
                [batch + 1],
                [batch + 1],
                [N_total],
                [batch * 16 + 1],
                [batch * 160, 8],
                [],
                [],
                [],
                [batch * 300, H, d_v],
                [batch * 300, H],
                [N_total, H, d_v],
                [],
                [],
                [],
            ],
            "Input type": [in_t] * 3
            + ["int"] * 5
            + ["Scalar"] * 3
            + ["float", "float", "c10::BFloat16", "float", "float", "float"],
            "Concrete Inputs": [""] * 8
            + [str(seq_len), "0.13523377886088009", "True"]
            + [""] * 6,
        },
    }
    return event


@register(
    "dsv3_mla_reduce_v1",
    category="dsv3",
    description="AITER MLA cross-split reduce (paired with mla_prefill_ps_asm_fwd)",
    model=(DSV3_EXT, "aiter_mla_reduce_v1"),
    defaults={
        "seq_len": 1024,
        "E": 16,
        "num_heads_q": 16,
        "head_dim": 192,
        "block_n": 1,
    },
    required_args=["seq_len"],
)
def _dsv3_mla_reduce_v1_event(args):
    """Event for aiter::mla_reduce_v1.

    Shape parameters match dsv3_mla_prefill_ps_asm_fwd (planner is shared).
    Partial-output rows are over-allocated by the persistent scheduler; we use
    the same conservative count (~2.4x the final tokens) the trace exhibits.
    """
    seq_len = args.seq_len
    batch = getattr(args, "E", None) or 16
    H = getattr(args, "num_heads_q", None) or 16
    d_qk = getattr(args, "head_dim", None) or 192
    d_v = d_qk - 64
    N_total = seq_len * batch
    n_partial = max(N_total * 2 + 4000, N_total + 100)
    event = {
        "name": "aiter::mla_reduce_v1",
        "args": {
            "Input Dims": [
                [n_partial, H, d_v],
                [n_partial, H],
                [batch * 5 + 1],
                [batch * 5, 2],
                [n_partial // 100],
                [],
                [N_total, H, d_v],
                [N_total, H],
            ],
            "Input type": [
                "float",
                "float",
                "int",
                "int",
                "int",
                "Scalar",
                "c10::BFloat16",
                "float",
            ],
            "Concrete Inputs": ["", "", "", "", "", "256", "", ""],
        },
    }
    return event


# ---------------------------------------------------------------------------
# DSV3 dominant pseudo ops (perf models in TraceLens core op_to_perf_model_class_map)
# ---------------------------------------------------------------------------
@register(
    "dsv3_mla_decode_fwd",
    category="dsv3_mla_decode",
    description="AITER paged MLA attention (pseudo_mla_decode_fwd: core ASM + reduce)",
    model=(CORE_OP_MAP, "pseudo_mla_decode_fwd"),
    defaults={
        "seq_len": 8677,
        "E": 64,
        "num_heads_q": 16,
        "head_dim": 576,
        "kv_dtype": "fp8",
        "n_ctx": 0,
        "ctx_qlen": 0,
    },
    required_args=["seq_len", "E", "num_heads_q", "head_dim"],
    trace_names=("pseudo_mla_decode_fwd",),
    csv_harness=True,
)
def _dsv3_mla_decode_fwd_event(args):
    """Event for ``pseudo_mla_decode_fwd`` (FP8 paged MLA decode).

    Resolved from the TraceLens core map (InferenceAttention subclass). Builds
    the chunk-stats annotation the model expects from the decode geometry:
    ``E`` decode sequences (q_len==1), each attending ``seq_len`` KV tokens.
    """
    batch = getattr(args, "E", None) or 64
    ctx = args.seq_len
    nhead = getattr(args, "num_heads_q", None) or 16
    qk = getattr(args, "head_dim", None) or 576
    # Decode: sq_i == 1 per sequence -> g_sq = batch, g_sqsq = batch,
    # g_sk = g_sqsk = batch * ctx.
    g_sq = batch
    g_sk = batch * ctx
    g_sqsq = batch
    g_sqsk = batch * ctx
    ann = (
        f"execute_0_context_0(sq0sk0sqsq0sqsk0)"
        f"_generation_{batch}(sq{g_sq}sk{g_sk}sqsq{g_sqsq}sqsk{g_sqsk})"
    )
    event = {
        "name": "pseudo_mla_decode_fwd",
        "args": {
            "Input Dims": [[batch, nhead, qk], [batch, 1, qk]],
            "Input type": ["c10::Float8_e4m3fn", "c10::Float8_e4m3fn"],
        },
        "annotation": ann,
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }
    return event


@register(
    "dsv3_moe_flydsl_stage1",
    category="dsv3_moe_flydsl",
    description="AITER FlyDSL FP4 MoE stage-1 GEMM (moe_gemm1_0)",
    model=(CORE_OP_MAP, "pseudo_op::moe_flydsl_stage1"),
    defaults={"M": 64, "K": 7168, "N": 256, "E": 257, "topk": 9, "block_m": 32},
    required_args=["M", "K", "N", "E", "topk"],
    trace_names=("pseudo_op::moe_flydsl_stage1",),
    csv_harness=True,
)
def _dsv3_moe_flydsl_stage1_event(args):
    """Event for ``pseudo_op::moe_flydsl_stage1`` (FP4 MoE gate+up GEMM)."""
    M = args.M
    K = getattr(args, "K", None) or 7168
    N = args.N
    E = getattr(args, "E", None) or 257
    topk = getattr(args, "topk", None) or 9
    event = _dsv3_flydsl_moe_event("pseudo_op::moe_flydsl_stage1", M, K, N, E, topk)
    return event


@register(
    "dsv3_moe_flydsl_stage2",
    category="dsv3_moe_flydsl",
    description="AITER FlyDSL FP4 MoE stage-2 GEMM (moe_gemm2)",
    model=(CORE_OP_MAP, "pseudo_op::moe_flydsl_stage2"),
    defaults={"M": 64, "K": 7168, "N": 256, "E": 257, "topk": 9, "block_m": 32},
    required_args=["M", "K", "N", "E", "topk"],
    trace_names=("pseudo_op::moe_flydsl_stage2",),
    csv_harness=True,
)
def _dsv3_moe_flydsl_stage2_event(args):
    """Event for ``pseudo_op::moe_flydsl_stage2`` (FP4 MoE down GEMM)."""
    M = args.M
    K = getattr(args, "K", None) or 7168
    N = args.N
    E = getattr(args, "E", None) or 257
    topk = getattr(args, "topk", None) or 9
    event = _dsv3_flydsl_moe_event("pseudo_op::moe_flydsl_stage2", M, K, N, E, topk)
    return event


# ---------------------------------------------------------------------------
# MXFP4 ops
# ---------------------------------------------------------------------------
@register(
    "gemm_afp4wfp4",
    category="ext_mxfp4",
    description="AITER MXFP4 GEMM (gemm_afp4wfp4_)",
    model=(PERF_MODEL_EXT, "gemm_afp4wfp4"),
    defaults={"M": 822, "N": 2112, "K": 3584},
    trace_names=("aiter::gemm_afp4wfp4_",),
)
def _gemm_afp4wfp4_event(args):
    """Event for ``aiter::gemm_afp4wfp4_`` (MXFP4 GEMM).

    Inputs are FP4 (packed as ``unsigned char`` in the trace). Output is BF16.
    """
    K = args.K
    N = args.N
    M = args.M
    SCALE_GROUP_SIZE = 32
    event = {
        "name": "aiter::gemm_afp4wfp4_",
        "args": {
            "Input Dims": [
                [M, K // 2],
                [N, K // 2],
                [M, K // SCALE_GROUP_SIZE],
                [N, K // SCALE_GROUP_SIZE],
                [],
                [M, N],
                [],
                [],
            ],
            "Input type": [
                "unsigned char",
                "unsigned char",
                "unsigned char",
                "unsigned char",
                "Scalar",
                "c10::BFloat16",
                "",
                "Scalar",
            ],
            "Input Strides": [
                [K // 2, 1],
                [K // 2, 1],
                [K // SCALE_GROUP_SIZE, 1],
                [K // SCALE_GROUP_SIZE, 1],
                [],
                [N, 1],
                [],
                [],
            ],
            "Concrete Inputs": ["", "", "", "", "15", "", "", "False"],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }
    return event


@register(
    "rope_cached_positions_2c_fwd_impl",
    category="ext_mxfp4",
    description="AITER 2-channel cached-positions forward RoPE",
    model=(PERF_MODEL_EXT, "aiter_rope_cached_positions_2c_fwd_impl"),
    defaults={"M": 822, "num_heads_q": 16, "num_heads_kv": 1, "head_dim": 64},
    required_args=["M"],
    trace_names=("aiter::rope_cached_positions_2c_fwd_impl",),
)
def _rope_cached_positions_2c_fwd_impl_event(args):
    """Event for ``aiter::rope_cached_positions_2c_fwd_impl``.

    Inputs:
      Input Dims[2] = input_x  (s, b, H_q,  d) BF16
      Input Dims[3] = input_y  (s, b, H_kv, d) BF16
    """
    M = args.M
    H_q = getattr(args, "num_heads_q", None) or 16
    H_kv = getattr(args, "num_heads_kv", None) or 1
    d = getattr(args, "head_dim", None) or 64
    d_cs = d // 2
    max_pos = max(M * 16, 4096)
    event = {
        "name": "aiter::rope_cached_positions_2c_fwd_impl",
        "args": {
            "Input Dims": [
                [1, M, H_q, d],
                [1, M, H_kv, d],
                [1, M, H_q, d],
                [1, M, H_kv, d],
                [max_pos, 1, 1, d_cs],
                [max_pos, 1, 1, d_cs],
                [1, M],
                [],
                [],
                [],
            ],
            "Input type": [
                "c10::BFloat16",
                "c10::BFloat16",
                "c10::BFloat16",
                "c10::BFloat16",
                "c10::BFloat16",
                "c10::BFloat16",
                "long int",
                "Scalar",
                "Scalar",
                "Scalar",
            ],
        },
    }
    return event


@register(
    "fused_flatten_mxfp4_quant",
    category="ext_mxfp4",
    description="AITER triton fused flatten + MXFP4 quant",
    model=(PERF_MODEL_EXT, "fused_flatten_mxfp4_quant"),
    defaults={"M": 822, "N": 7168, "group_size": 128},
    required_args=["M", "N"],
    trace_names=("sglang_profiler::fused_mxfp4_quant_fused_flatten_mxfp4_quant",),
)
def _fused_flatten_mxfp4_quant_event(args):
    """Event for ``sglang_profiler::fused_mxfp4_quant_fused_flatten_mxfp4_quant``."""
    M = args.M
    N = args.N
    group_size = getattr(args, "group_size", None) or 128
    N2 = group_size
    N1 = N // group_size
    event = {
        "name": "sglang_profiler::fused_mxfp4_quant_fused_flatten_mxfp4_quant",
        "args": {
            "Input Dims": [[M, N1, N2]],
            "Input type": ["c10::BFloat16"],
            "Input Strides": [[N1 * N2, N2, 1]],
        },
    }
    return event


@register(
    "fused_rms_mxfp4_quant",
    category="ext_mxfp4",
    description="AITER triton fused RMSNorm + MXFP4 quant",
    model=(RMSNORM_EXT, "fused_rms_mxfp4_quant"),
    defaults={"M": 822, "N": 7168},
    trace_names=("sglang_profiler::fused_mxfp4_quant_fused_rms_mxfp4_quant",),
)
def _fused_rms_mxfp4_quant_event(args):
    """Event for ``sglang_profiler::fused_mxfp4_quant_fused_rms_mxfp4_quant``.

    Single-input (no x2, no res1) variant, matching the simplest call shape:
        x1:        (M, N1) BF16
        x1_weight: (N1,)   BF16
    """
    N = args.N
    M = args.M
    event = {
        "name": "sglang_profiler::fused_mxfp4_quant_fused_rms_mxfp4_quant",
        "args": {
            "Input Dims": [[M, N], [N], []],
            "Input type": ["c10::BFloat16", "c10::BFloat16", "Scalar"],
            "Input Strides": [[N, 1], [1], []],
        },
    }
    return event


# ---------------------------------------------------------------------------
# ATOM FlyDSL ops (tests/ has no test_<key> for these yet, so only the perf
# model is exercised)
# ---------------------------------------------------------------------------
@register(
    "atom_flydsl_preshuffle_gemm_a8",
    category="atom_flydsl",
    description="AITER FlyDSL A8W8 preshuffle GEMM (flydsl_preshuffle_gemm_a8)",
    model=(PERF_MODEL_EXT, "gemm_a8w8_blockscale"),
    defaults={"M": 512, "N": 4096, "K": 7168},
    trace_names=(
        "aiter::gemm_a8w8_bpreshuffle",
        "vllm::_rocm_aiter_preshuffled_per_token_w8a8_gemm",
    ),
    csv_harness=True,
)
def _atom_flydsl_preshuffle_gemm_a8_event(args):
    """Event for ``aiter::gemm_a8w8_bpreshuffle`` (FlyDSL A8W8 GEMM).

    Maps to ``gemm_a8w8_blockscale``: FLOPs ``2*M*N*K``, bytes A/B = 1 byte
    (FP8), output = 2 bytes (BF16). The bpreshuffle layout is layout-only, so
    flops/bytes match the block-scale model.
    """
    K = args.K
    N = args.N
    M = args.M
    in_t = _dtype_from_args(args, "in_dtype", "c10::Float8_e4m3fn")
    w_t = _dtype_from_args(args, "w_dtype", "c10::Float8_e4m3fn")
    scl_t = _dtype_from_args(args, "scale_dtype", "float")
    event = {
        "name": "aiter::gemm_a8w8_bpreshuffle",
        "args": {
            "Input Dims": [[M, K], [N, K], [M, 1], [N, 1]],
            "Input type": [in_t, w_t, scl_t, scl_t],
            "Input Strides": [[K, 1], [K, 1], [1, 1], [1, 1]],
        },
        "kernel_names": ["placeholder_kernel"],
        "kernel_details": [{"name": "placeholder_kernel"}],
    }
    return event


@register(
    "atom_flydsl_gdr_decode",
    category="atom_flydsl",
    description="AITER FlyDSL gated-delta-rule decode (flydsl_gdr_decode)",
    model=(ATTN_EXT, "gdn_attention_core"),
    defaults={"seq_len": 128, "num_heads_kv": 8, "head_dim": 128},
    required_args=["seq_len"],
    trace_names=("aiter::linear_attention_with_output_base",),
    csv_harness=True,
)
def _atom_flydsl_gdr_decode_event(args):
    """Event for ``aiter::linear_attention_with_output_base`` (FlyDSL GDR).

    Maps to ``gdn_attention_core`` -- the op signature
    ``(mixed_qkv, b, a, core_attn_out, layer_name)`` matches the layout the
    model parses. ``--seq_len`` is the GDN total-token count (decode: one token
    per sequence), injected via the GDN ``c_sq`` annotation field.
    """
    return _gdn_event(
        "aiter::linear_attention_with_output_base",
        args,
        H_K=max(1, args.num_heads_kv // 2),
        annotation=f"attn_0_0_{args.seq_len}_0_0_0_0",
    )


# ---------------------------------------------------------------------------
# DSV4 triage-extension ops (perf models in the file named by
# DSV4_TRIAGE_EXTENSION)
# ---------------------------------------------------------------------------
@register(
    "dsv4_mhc_pre_gemm_sqrsum",
    category="dsv4",
    description="DSV4 mHC pre GEMM + sum-of-squares (aiter)",
    model=(DSV4_EXT, "aiter::mhc_pre_gemm_sqrsum"),
    defaults={"M": 1819, "N": 7168},
)
def _dsv4_mhc_pre_gemm_sqrsum_event(args):
    M = args.M
    C = args.N
    hc_mult = 4
    hc_mult3 = hc_mult * 2 + hc_mult * hc_mult  # 24
    K = hc_mult * C  # 28672
    split_k = getattr(args, "split_k", None) or 16
    event = {
        "name": "aiter::mhc_pre_gemm_sqrsum",
        "args": {
            "Input Dims": [
                [split_k, M, hc_mult3],
                [split_k, M],
                [M, hc_mult, C],
                [hc_mult3, K],
                [],
            ],
            "Input type": ["float", "float", _BF16, "float", "Scalar"],
        },
    }
    return event


@register(
    "dsv4_mhc_pre_big_fuse",
    category="dsv4",
    description="DSV4 mHC pre RMS+Sinkhorn+mix fuse (aiter)",
    model=(DSV4_EXT, "aiter::mhc_pre_big_fuse"),
    defaults={"M": 1819, "N": 7168},
)
def _dsv4_mhc_pre_big_fuse_event(args):
    M = args.M
    C = args.N
    hc_mult = 4
    hc_mult3 = hc_mult * 2 + hc_mult * hc_mult
    split_k = getattr(args, "split_k", None) or 16
    event = {
        "name": "aiter::mhc_pre_big_fuse",
        "args": {
            "Input Dims": [
                [M, hc_mult, 1],
                [M, hc_mult, hc_mult],
                [M, C],
                [split_k, M, hc_mult3],
                [split_k, M],
                [3],
                [hc_mult3],
                [M, hc_mult, C],
                [],
                [],
                [],
                [],
                [],
            ],
            "Input type": [
                "float",
                "float",
                _BF16,
                "float",
                "float",
                "float",
                "float",
                _BF16,
                "Scalar",
                "Scalar",
                "Scalar",
                "Scalar",
                "Scalar",
            ],
            "Concrete Inputs": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "1e-06",
                "1e-06",
                "1e-06",
                "2.",
                "20",
            ],
        },
    }
    return event


@register(
    "dsv4_mhc_post",
    category="dsv4",
    description="DSV4 mHC post stream-merge (aiter)",
    model=(DSV4_EXT, "aiter::mhc_post"),
    defaults={"M": 1819, "N": 7168},
)
def _dsv4_mhc_post_event(args):
    M = args.M
    C = args.N
    hc_mult = 4
    event = {
        "name": "aiter::mhc_post",
        "args": {
            "Input Dims": [
                [M, hc_mult, C],
                [M, C],
                [M, hc_mult, C],
                [M, hc_mult],
                [M, hc_mult, hc_mult],
            ],
            "Input type": [_BF16, _BF16, _BF16, "float", "float"],
        },
    }
    return event


@register(
    "dsv4_pa_sparse_prefill_opus",
    category="dsv4",
    description="DSV4 sparse paged prefill MLA attention (aiter)",
    model=(DSV4_EXT, "aiter::pa_sparse_prefill_opus_fwd"),
    defaults={"M": 1819, "num_heads_q": 32, "head_dim": 512},
)
def _dsv4_pa_sparse_prefill_opus_event(args):
    N = args.M
    H = getattr(args, "num_heads_q", None) or 32
    D = getattr(args, "head_dim", None) or 512
    nnz_prefix = 2095488
    nnz_extend = 232832
    total_pages = 329728
    event = {
        "name": "aiter::pa_sparse_prefill_opus_fwd",
        "args": {
            "Input Dims": [
                [N, H, D],
                [total_pages, D],
                [nnz_prefix],
                [N + 1],
                [N, D],
                [nnz_extend],
                [N + 1],
                [H],
                [N, H, D],
                [],
            ],
            "Input type": [
                _BF16,
                _BF16,
                "int",
                "int",
                _BF16,
                "int",
                "int",
                "float",
                _BF16,
                "Scalar",
            ],
        },
    }
    return event


@register(
    "dsv4_opus_gemm_a16w16",
    category="dsv4",
    description="DSV4 batched BF16 GEMM (aiter opus split-K)",
    model=(DSV4_EXT, "aiter::_opus_gemm_a16w16_tune_raw"),
    defaults={"M": 1819, "N": 384, "K": 7168},
)
def _dsv4_opus_gemm_a16w16_event(args):
    M, N, K = args.M, args.N, args.K
    event = {
        "name": "aiter::_opus_gemm_a16w16_tune_raw",
        "args": {
            "Input Dims": [[1, M, K], [1, N, K], [1, M, N], [], [], []],
            "Input type": [_BF16, _BF16, _BF16, "", "Scalar", "Scalar"],
        },
    }
    return event


@register(
    "dsv4_gemm_a8w8_blockscale_bpreshuffle_asm",
    category="dsv4",
    description="DSV4 FP8 block-scaled GEMM, B preshuffle (aiter ASM)",
    model=(DSV4_EXT, "aiter::_gemm_a8w8_blockscale_bpreshuffle_asm"),
    defaults={"M": 1819, "N": 2048, "K": 7168},
)
def _dsv4_gemm_a8w8_blockscale_bpreshuffle_asm_event(args):
    M, N, K = args.M, args.N, args.K
    sk = (K + 127) // 128
    sn = (N + 127) // 128
    event = {
        "name": "aiter::_gemm_a8w8_blockscale_bpreshuffle_asm",
        "args": {
            "Input Dims": [
                [M, K],
                [N, K],
                [M, N],
                [M, sk],
                [sn, sk],
                [],
                [],
                [],
                [],
                [1, N],
            ],
            "Input type": [
                _FP8,
                _FP8,
                _BF16,
                "float",
                "float",
                "",
                "Scalar",
                "",
                "Scalar",
                "float",
            ],
        },
    }
    return event


@register(
    "dsv4_dynamic_per_group_scaled_quant",
    category="dsv4",
    description="DSV4 per-group dynamic MX-FP8 quant (aiter)",
    model=(DSV4_EXT, "aiter::dynamic_per_group_scaled_quant"),
    defaults={"M": 1819, "N": 7168, "group_size": 32},
    required_args=["M", "N"],
)
def _dsv4_dynamic_per_group_scaled_quant_event(args):
    M = args.M
    K = args.N
    g = getattr(args, "group_size", None) or 32
    sk = K // g
    event = {
        "name": "aiter::dynamic_per_group_scaled_quant",
        "args": {
            "Input Dims": [[M, K], [M, K], [M, sk], [], [], [], []],
            "Input type": [_FP8, _BF16, _E8M0, "Scalar", "Scalar", "", "Scalar"],
            "Input Strides": [[K, 1], [K, 1], [sk, 1], [], [], [], []],
            "Concrete Inputs": ["", "", "", str(g), "False", "", "1"],
        },
    }
    return event


@register(
    "dsv4_topk_softplus",
    category="dsv4",
    description="DSV4 MoE router topk + sqrt(softplus) (aiter)",
    model=(DSV4_EXT, "aiter::topk_softplus"),
    defaults={"M": 1819, "N": 384, "topk": 6},
)
def _dsv4_topk_softplus_event(args):
    T = args.M
    E = args.N
    k = getattr(args, "topk", None) or 6
    event = {
        "name": "aiter::topk_softplus",
        "args": {
            "Input Dims": [[T, k], [T, k], [T, E], [E], [], [], []],
            "Input type": ["float", "int", _BF16, _BF16, "Scalar", "Scalar", ""],
            "Concrete Inputs": ["", "", "", "", "True", "2.5", ""],
        },
    }
    return event


@register(
    "dsv4_fused_dynamic_mx_quant_moe_sort",
    category="dsv4",
    description="DSV4 fused MX-FP8 quant + MoE sort (aiter)",
    model=(DSV4_EXT, "aiter::fused_dynamic_mx_quant_moe_sort_hip"),
    defaults={"M": 32, "N": 7168, "E": 384, "topk": 6, "group_size": 32},
    required_args=["M", "N", "E", "topk"],
)
def _dsv4_fused_dynamic_mx_quant_moe_sort_event(args):
    R = args.M
    C = args.N
    g = getattr(args, "group_size", None) or 32
    E = getattr(args, "E", None) or 384
    topk = getattr(args, "topk", None) or 6
    block = getattr(args, "block_m", None) or 32
    sk = C // g
    # sorted-id buffer size mirrors aiter.moe_sorting: R*topk + E*block - R
    n_sorted = R * topk + E * block - R
    s_pad = ((n_sorted + 31) // 32) * 32
    event = {
        "name": "aiter::fused_dynamic_mx_quant_moe_sort_hip",
        "args": {
            "Input Dims": [[R, C], [s_pad, sk], [R, C], [n_sorted], [2], [], [], []],
            "Input type": [
                _FP8,
                _E8M0,
                _BF16,
                "int",
                "int",
                "Scalar",
                "Scalar",
                "Scalar",
            ],
            "Input Strides": [[C, 1], [sk, 1], [C, 1], [1], [1], [], [], []],
            "Concrete Inputs": ["", "", "", "", "", str(g), str(g), str(g)],
        },
    }
    return event


# ---------------------------------------------------------------------------
# Ops validated only from a report directory (see _CSV_ONLY_OPS)
# ---------------------------------------------------------------------------
for _key, _category, _description, _trace_name in _CSV_ONLY_OPS:
    register(
        _key,
        category=_category,
        description=_description,
        trace_names=(_trace_name,),
    )(None)


# ---------------------------------------------------------------------------
# Kimi-K3 ops (perf models in the file named by KIMI_K3_TRIAGE_EXTENSION)
# ---------------------------------------------------------------------------
@register(
    "kimi_fused_kda_decode",
    category="kimi_k3",
    description="Kimi-K3 fused KDA decode (conv + recurrence + gated RMSNorm)",
    model=(KIMI_EXT, "kimi_fused_kda_decode"),
    defaults={"seq_len": 7, "num_heads_q": 12, "head_dim": 128, "E": 2732},
    required_args=["seq_len"],
    trace_names=("_C::fused_kda_decode",),
)
def _kimi_fused_kda_decode_event(args):
    """Event for ``_C::fused_kda_decode`` (Kimi-K3 fused KDA decode)."""
    T = getattr(args, "seq_len", None) or getattr(args, "M", None) or 7
    H = getattr(args, "num_heads_q", None) or getattr(args, "num_heads", None) or 12
    d = getattr(args, "head_dim", None) or 128
    W_c = getattr(args, "conv_width", None) or 4
    d_x = 3 * H * d
    event = {
        "name": "_C::fused_kda_decode",
        "args": {
            "Input Dims": [
                [T, d_x],
                [3, W_c, H * d],
                [],
                [64, d_x, W_c - 1],
                [1, T, H, d],
                [1, T, H],
                [H],
                [H * d],
                [T],
                [64, H, d, d],
                [1, T, H, d],
                [],
                [T, H, d],
                [d],
                [],
            ],
            "Input type": [
                "c10::BFloat16",
                "float",
                "",
                "c10::BFloat16",
                "c10::BFloat16",
                "c10::BFloat16",
                "float",
                "float",
                "int",
                "float",
                "c10::BFloat16",
                "Scalar",
                "c10::BFloat16",
                "float",
                "Scalar",
            ],
        },
    }
    return event


@register(
    "kimi_situ_and_mul",
    category="kimi_k3",
    description="Kimi SituGLU (_C::situ_and_mul)",
    model=(KIMI_EXT, "kimi_situ_and_mul"),
    defaults={"M": 7, "N": 768},
    trace_names=("_C::situ_and_mul",),
)
def _kimi_situ_and_mul_event(args):
    """Event for ``_C::situ_and_mul``."""
    T = getattr(args, "M", None) or 7
    D = getattr(args, "N", None) or 768
    event = {
        "name": "_C::situ_and_mul",
        "args": {
            "Input Dims": [[T, D], [T, 2 * D], [], [], []],
            "Input type": ["c10::BFloat16", "c10::BFloat16", "Scalar", "Scalar", ""],
            "Input Strides": [[D, 1], [2 * D, 1], [], [], []],
            "Concrete Inputs": ["", "", "4.", "25.", ""],
        },
    }
    return event


@register(
    "kimi_static_per_tensor_quant",
    category="kimi_k3",
    description="AITER static per-tensor quant (Kimi MLA path)",
    model=(KIMI_EXT, "kimi_static_per_tensor_quant"),
    defaults={"M": 7, "N": 6912},
    trace_names=("aiter::static_per_tensor_quant",),
)
def _kimi_static_per_tensor_quant_event(args):
    """Event for ``aiter::static_per_tensor_quant``."""
    T = getattr(args, "M", None) or 7
    N = getattr(args, "N", None) or 6912
    event = {
        "name": "aiter::static_per_tensor_quant",
        "args": {
            "Input Dims": [[T, N], [T, N], []],
            "Input type": ["c10::Float8_e4m3fn", "c10::BFloat16", "float"],
        },
    }
    return event


@register(
    "kimi_moe_sorting_opus_fwd",
    category="kimi_k3",
    description="AITER opus MoE sorting (Kimi-K3)",
    model=(KIMI_EXT, "kimi_moe_sorting_opus_fwd"),
    defaults={"M": 7, "topk": 16, "E": 896, "block_m": 32},
    required_args=["M"],
    trace_names=("aiter::moe_sorting_opus_fwd",),
)
def _kimi_moe_sorting_opus_fwd_event(args):
    """Event for ``aiter::moe_sorting_opus_fwd``."""
    T = getattr(args, "M", None) or 7
    topk = getattr(args, "topk", None) or 16
    event = {
        "name": "aiter::moe_sorting_opus_fwd",
        "args": {
            "Input Dims": [
                [T, topk],
                [T, topk],
                [28768],
                [28768],
                [899],
                [2],
                [0, 0],
                [],
                [],
                [],
                [],
                [118528],
                [],
                [],
                [],
                [],
            ],
            "Input type": [
                "int",
                "float",
                "int",
                "float",
                "int",
                "int",
                "c10::BFloat16",
                "Scalar",
                "Scalar",
                "",
                "",
                "unsigned char",
                "Scalar",
                "",
                "",
                "",
            ],
        },
    }
    return event


@register(
    "kimi_aten_addmm_",
    category="kimi_k3",
    description="In-place aten::addmm_ (Kimi-K3 decode GEMM)",
    model=(KIMI_EXT, "kimi_aten_addmm_inplace"),
    defaults={"M": 7, "N": 896, "K": 3584},
    trace_names=("aten::addmm_",),
)
def _kimi_aten_addmm__event(args):
    """Event for ``aten::addmm_``."""
    M = getattr(args, "M", None) or 7
    N = getattr(args, "N", None) or 896
    K = getattr(args, "K", None) or 3584
    event = {
        "name": "aten::addmm_",
        "args": {
            "Input Dims": [[M, N], [M, K], [K, N], [], []],
            "Input type": [
                "c10::BFloat16",
                "c10::BFloat16",
                "c10::BFloat16",
                "Scalar",
                "Scalar",
            ],
            "Input Strides": [[N, 1], [K, 1], [1, N], [], []],
        },
    }
    return event


@register(
    "kimi_gather_and_maybe_dequant_cache",
    category="kimi_k3",
    description="vLLM FP8 MLA KV gather + dequant",
    model=(KIMI_EXT, "kimi_gather_and_maybe_dequant_cache"),
    defaults={"seq_len": 1024, "head_dim": 576},
    required_args=["seq_len"],
    trace_names=("_C_cache_ops::gather_and_maybe_dequant_cache",),
)
def _kimi_gather_and_maybe_dequant_cache_event(args):
    """Event for ``_C_cache_ops::gather_and_maybe_dequant_cache``."""
    n_kv = getattr(args, "seq_len", None) or getattr(args, "M", None) or 1024
    d_kv = getattr(args, "head_dim", None) or 576
    event = {
        "name": "_C_cache_ops::gather_and_maybe_dequant_cache",
        "args": {
            "Input Dims": [[n_kv, d_kv], [n_kv, d_kv]],
            "Input type": ["c10::Float8_e4m3fn", "c10::BFloat16"],
        },
        "annotation": (
            f"execute_{n_kv}_context_1(sq{n_kv}sk{n_kv}sqsq0sqsk{n_kv})"
            f"_generation_0(sq0sk0sqsq0sqsk0)"
        ),
    }
    return event
