name: Format (auto-fix)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black usort

      - name: Run formatters
        run: |
          usort format .
          black .

      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply formatting (usort + black)"
          branch: ${{ github.head_ref }}
